import type { BlogPost } from "@/lib/blog";

const areAmericansActuallyDrinkingLess: BlogPost = {
  slug: "are-americans-actually-drinking-less",
  title: "Are Americans Actually Drinking Less? The Numbers Say Something Is Changing.",
  shortTitle: "Are Americans Actually Drinking Less?",
  seoTitle: "Are Americans Drinking Less Alcohol? What the Latest Data Shows",
  seoDescription: "Federal and Gallup data show Americans are drinking less, binge drinking is declining and alcohol-free alternatives are growing. Here is what may be changing.",
  category: "News & Culture",
  excerpt: "Mocktails and sober curiosity may look like trends, but the latest national data suggest something measurable is happening to American drinking.",
  publishedAt: "September 8, 2026",
  publishedDate: "2026-09-08",
  publishedTime: "12:45",
  readTime: "11 min read",
  author: "Lyra",
  image: "/images/blog/are-americans-drinking-less.png",
  heroAlt: "Four friends sharing dinner at a waterfront restaurant with wine, beer, an alcohol-free drink and sparkling water on the table.",
  relatedSlugs: ["are-people-drinking-less-alcohol", "coffee-raves-sober-nightlife", "do-alcohol-free-drinks-help-you-drink-less"],
  sources: [
    { name: "SAMHSA", title: "Key Substance Use and Mental Health Indicators in the United States: Results from the 2025 National Survey on Drug Use and Health", url: "https://www.samhsa.gov/data/sites/default/files/reports/rpt57150/2025-nsduh-annual-national-html/2025-nsduh-annual-national.htm" },
    { name: "Gallup", title: "Americans' Drinking Remains at Record Low", url: "https://news.gallup.com/poll/713534/americans-drinking-remains-record-low.aspx" },
    { name: "National Institute on Alcohol Abuse and Alcoholism", title: "Alcohol Treatment in the United States", url: "https://www.niaaa.nih.gov/alcohols-effects-health/alcohol-topics-z/alcohol-facts-and-statistics/alcohol-treatment-united-states" },
  ],
  body: [
    { type: "paragraph", text: "For years, it has been easy to look at the rise of mocktails, alcohol-free beer, Dry January, sober bars and sober-curious social media and wonder whether any of it actually means anything." },
    { type: "paragraph", text: "Maybe we're just seeing more of it because we're looking for it." },
    { type: "paragraph", text: "Maybe younger people post about drinking less while everybody else keeps ordering exactly what they always did." },
    { type: "paragraph", text: "Maybe alcohol-free menus are simply another trend that restaurants figured out how to sell." },
    { type: "paragraph", text: "But the latest national numbers are getting harder to dismiss." },
    { type: "paragraph", text: "Americans really do appear to be drinking less." },
    { type: "paragraph", text: "Not everyone. Not everywhere. And certainly not enough to make alcohol-related harm disappear." },
    { type: "paragraph", text: "But across several different measures, something is moving." },
    { type: "quote", text: "The interesting story may not be that America is becoming sober. It may be that drinking is slowly becoming optional." },
    { type: "heading", text: "Start With the Biggest Number" },
    { type: "paragraph", text: "The federal government's National Survey on Drug Use and Health gives us one of the clearest pictures." },
    { type: "paragraph", text: "In 2021, 47.4% of Americans age 12 and older reported drinking alcohol in the previous month." },
    { type: "paragraph", text: "By 2025, that had fallen to 44.4%, or about 129.1 million people." },
    { type: "paragraph", text: "That sounds like three percentage points. Across the United States, it represents millions of people and a measurable shift in drinking behavior." },
    { type: "paragraph", text: "And the decline isn't isolated to one age group." },
    { type: "paragraph", text: "Among adults ages 18 to 25, past-month drinking fell from 50.9% in 2021 to 46.2% in 2025." },
    { type: "paragraph", text: "Among adults 26 and older, it fell from 51.5% to 48.4%." },
    { type: "paragraph", text: "Among adolescents ages 12 to 17, it dropped from 7.2% to 5.9%." },
    { type: "paragraph", text: "Different generations. Same general direction." },
    { type: "heading", text: "People Aren't Just Drinking Less Often" },
    { type: "paragraph", text: "The binge-drinking numbers are moving too." },
    { type: "paragraph", text: "In 2021, 21.7% of Americans age 12 and older reported binge drinking in the previous month." },
    { type: "paragraph", text: "In 2025, that figure was 19.5%." },
    { type: "paragraph", text: "Among young adults ages 18 to 25, it fell from 30.0% to 26.7%." },
    { type: "paragraph", text: "Heavy alcohol use also declined over the 2021-to-2025 period for the population overall." },
    { type: "paragraph", text: "That matters because there are at least two different stories we could be telling." },
    { type: "paragraph", text: "One would be: fewer people drink, but the people who still drink are drinking just as heavily." },
    { type: "paragraph", text: "The other is: both participation and some riskier patterns of drinking are declining." },
    { type: "paragraph", text: "The national data increasingly looks more like the second story." },
    { type: "quote", text: "This isn't only about who's ordering alcohol. It's also about how people are drinking when they do." },
    { type: "heading", text: "Gallup Is Seeing the Same Thing" },
    { type: "paragraph", text: "Another dataset tells a remarkably similar story." },
    { type: "paragraph", text: "Gallup has asked Americans about alcohol for decades." },
    { type: "paragraph", text: "In its 2026 survey, 54% of U.S. adults said they drink alcohol." },
    { type: "paragraph", text: "That's tied with 2025 for the lowest level Gallup has recorded since it began tracking the question in 1939." },
    { type: "paragraph", text: "As recently as 2023, the number was 62%. It fell to 58% in 2024, then 54% in 2025, and remained there in 2026." },
    { type: "paragraph", text: "Among people who do drink, Gallup found another record: only 13% said they sometimes drink more than they think they should." },
    { type: "paragraph", text: "Two surveys do not measure alcohol use in exactly the same way. NSDUH asks about recent alcohol use among people age 12 and older, while Gallup asks U.S. adults whether they drink." },
    { type: "paragraph", text: "But when different measures point in the same direction, the trend becomes harder to explain away." },
    { type: "heading", text: "Americans Are Changing What They Believe About Alcohol Too" },
    { type: "paragraph", text: "Drinking behavior isn't changing in isolation." },
    { type: "paragraph", text: "Our beliefs about drinking are changing with it." },
    { type: "paragraph", text: "Gallup found that 51% of Americans now believe drinking one or two alcoholic beverages per day is bad for health." },
    { type: "paragraph", text: "In 2001, only 27% thought that. Back then, 22% actually believed moderate drinking was good for health." },
    { type: "paragraph", text: "Think about how much cultural baggage sits inside that change." },
    { type: "paragraph", text: "For years, we heard about the Mediterranean diet. Red wine. Heart health. A glass with dinner. Everything in moderation." },
    { type: "paragraph", text: "Alcohol wasn't necessarily presented as healthy, but moderate drinking often carried a strange health halo." },
    { type: "paragraph", text: "That halo is fading." },
    { type: "paragraph", text: "Cancer research is getting more attention. Sleep matters more. Fitness matters more. People track recovery on watches and notice what alcohol does to the next morning." },
    { type: "paragraph", text: "Increasingly, people seem willing to question whether the drink is worth the trade." },
    { type: "heading", text: "This Isn't Just Gen Z" },
    { type: "paragraph", text: "Gen Z gets most of the headlines." },
    { type: "paragraph", text: "And younger adults absolutely matter here." },
    { type: "paragraph", text: "But this is not simply a story about one alcohol-free generation replacing another." },
    { type: "paragraph", text: "Young people still drink." },
    { type: "paragraph", text: "In the federal data, 26.7% of adults ages 18 to 25 reported binge drinking in the previous month in 2025." },
    { type: "paragraph", text: "That's hardly an alcohol-free generation." },
    { type: "paragraph", text: "What younger adults may be helping normalize is something that used to require explanation: not drinking tonight." },
    { type: "paragraph", text: "Not forever. Not because something terrible happened. Not because you're driving. Just because you don't want alcohol tonight." },
    { type: "quote", text: "Not drinking tonight is becoming a complete sentence." },
    { type: "image", src: "/images/blog/alcohol-free-drinks-growing-popularity.png", alt: "A shopper browsing a large alcohol-free beverage section with nonalcoholic beer, wine, spirits and botanical drinks.", caption: "Alcohol-free choices are moving from the bottom shelf toward becoming a normal part of the beverage aisle." },
    { type: "heading", text: "Alcohol-Free Drinks Are Becoming Part of the Picture" },
    { type: "paragraph", text: "Gallup asked Americans about nonalcoholic alternatives for the first time this year." },
    { type: "paragraph", text: "Seventeen percent said they had consumed nonalcoholic beer, wine or spirits instead of an alcoholic drink during the previous year." },
    { type: "paragraph", text: "Among people who currently drink alcohol, that number was 20%." },
    { type: "paragraph", text: "And among drinkers using nonalcoholic alternatives, 38% said they were consuming more of them than they used to, compared with 17% who said they were consuming less." },
    { type: "paragraph", text: "That's interesting because alcohol-free drinks aren't only being purchased by sober people." },
    { type: "paragraph", text: "Drinkers are using them too." },
    { type: "paragraph", text: "Maybe someone has a beer and then switches to an NA beer." },
    { type: "paragraph", text: "Maybe wine is still part of Saturday dinner but not Tuesday dinner." },
    { type: "paragraph", text: "Maybe someone wants the ritual without the alcohol." },
    { type: "paragraph", text: "Maybe they're doing a temporary break. Maybe they're curious. Maybe they simply like the drink." },
    { type: "quote", text: "Alcohol-free doesn't have to mean alcohol-never. Sometimes it just means not this one." },
    { type: "heading", text: "Maybe That's Why This Feels Different" },
    { type: "paragraph", text: "Older conversations about sobriety often revolved around a binary." },
    { type: "paragraph", text: "You drank. Or you didn't." },
    { type: "paragraph", text: "For people with alcohol use disorder, that distinction can be incredibly important." },
    { type: "paragraph", text: "But it doesn't describe everybody changing their drinking today." },
    { type: "paragraph", text: "There is now a much larger middle." },
    { type: "list", items: [
      "People taking a month off.",
      "People drinking only on weekends.",
      "People alternating alcoholic and alcohol-free drinks.",
      "People quietly removing the nightly wine.",
      "People tracking how they sleep.",
      "People deciding three drinks isn't worth tomorrow.",
      "People who haven't decided whether they're quitting forever.",
    ] },
    { type: "paragraph", text: "That middle is exactly where the phrase sober curious found an audience." },
    { type: "paragraph", text: "It gave people permission to investigate alcohol without first declaring that they had a problem." },
    { type: "heading", text: "Alcohol Use Disorder Is Still a Very Big Problem" },
    { type: "paragraph", text: "The broader decline in drinking should not be confused with the problem disappearing." },
    { type: "paragraph", text: "The 2025 federal survey estimated that 25.7 million Americans age 12 and older had alcohol use disorder during the previous year." },
    { type: "paragraph", text: "That is tens of millions of people." },
    { type: "paragraph", text: "And treatment remains an enormous gap." },
    { type: "paragraph", text: "NIAAA reports that in 2024 only 7.6% of people age 12 and older with past-year alcohol use disorder received alcohol treatment during the year." },
    { type: "paragraph", text: "So it is possible to hold two ideas at once." },
    { type: "paragraph", text: "The national drinking trend can be encouraging." },
    { type: "paragraph", text: "And alcohol-related problems can remain enormous." },
    { type: "quote", text: "A trend can be encouraging without the problem becoming small." },
    { type: "heading", text: "Why Are Americans Drinking Less?" },
    { type: "paragraph", text: "This is where we need to be careful." },
    { type: "paragraph", text: "We have strong evidence that drinking behavior is changing." },
    { type: "paragraph", text: "We have much weaker evidence explaining exactly why." },
    { type: "paragraph", text: "There probably isn't one reason." },
    { type: "paragraph", text: "Health awareness appears to matter. Gallup's changing health-risk perceptions line up with the decline in drinking." },
    { type: "paragraph", text: "Alcohol-free products are more available." },
    { type: "paragraph", text: "Social media has made sober curiosity visible." },
    { type: "paragraph", text: "Fitness and sleep culture have made alcohol's next-day effects harder to ignore." },
    { type: "paragraph", text: "Younger generations may have different attitudes toward nightlife." },
    { type: "paragraph", text: "Cost may matter." },
    { type: "paragraph", text: "Changes in cannabis use may matter." },
    { type: "paragraph", text: "GLP-1 medications are being studied for possible effects on alcohol craving, but it would be premature to credit them with a national decline in drinking." },
    { type: "paragraph", text: "Culture rarely changes for one reason." },
    { type: "quote", text: "We can measure the decline more confidently than we can explain every reason behind it." },
    { type: "image", src: "/images/blog/why-americans-are-drinking-less.png", alt: "People walking, running, cycling and visiting a farmers market along a lively waterfront on a bright weekend morning.", caption: "The drinking shift may be connected to something larger: more people appear to be thinking about what they want from the morning after, not only the night before." },
    { type: "heading", text: "What About Marijuana?" },
    { type: "paragraph", text: "There's another complication." },
    { type: "paragraph", text: "Less alcohol doesn't necessarily mean less substance use." },
    { type: "paragraph", text: "The 2025 federal data show marijuana use increased for the population age 12 and older over the 2021-to-2025 period, even as alcohol use declined." },
    { type: "paragraph", text: "The pattern differs by age. Among young adults ages 18 to 25, past-month marijuana use actually declined over that period, while the overall increase was driven elsewhere in the population." },
    { type: "paragraph", text: "Some people may substitute cannabis for alcohol. Some use both. Some use neither." },
    { type: "paragraph", text: "The national data alone cannot tell us how much substitution explains the alcohol decline." },
    { type: "paragraph", text: "That's why it would be misleading to turn declining drinking into a sweeping claim that Americans are becoming universally more sober." },
    { type: "paragraph", text: "We're talking about alcohol." },
    { type: "paragraph", text: "And specifically, we're seeing evidence that alcohol occupies a slightly smaller place in American life than it did a few years ago." },
    { type: "heading", text: "The Marketplace Is Starting to Look Different" },
    { type: "paragraph", text: "This is where several pieces of Nova's recent coverage start connecting." },
    { type: "paragraph", text: "We've watched alcohol companies deal with softer demand." },
    { type: "paragraph", text: "We've watched alcohol-free beverages become more sophisticated." },
    { type: "paragraph", text: "We've watched coffee raves and daytime social events grow." },
    { type: "paragraph", text: "We've watched restaurants give nonalcoholic drinks actual menu space instead of offering club soda as an afterthought." },
    { type: "paragraph", text: "Any one of those could be dismissed as a trend." },
    { type: "paragraph", text: "Together with the federal and Gallup numbers, they begin looking more like symptoms of something larger." },
    { type: "quote", text: "Culture usually changes before we agree on what to call the change." },
    { type: "continueReading", text: "One place this cultural shift is becoming visible is nightlife itself. We looked at why coffee raves and sober daytime events are giving people somewhere different to go.", slug: "coffee-raves-sober-nightlife" },
    { type: "heading", text: "This Doesn't Mean Alcohol Is Going Away" },
    { type: "paragraph", text: "It isn't." },
    { type: "paragraph", text: "About 129.1 million Americans age 12 and older reported drinking alcohol in the previous month in 2025." },
    { type: "paragraph", text: "Bars aren't disappearing. Wine isn't disappearing. Beer isn't disappearing. Weddings will still have open bars." },
    { type: "paragraph", text: "And millions of people will continue to experience serious alcohol-related harm." },
    { type: "paragraph", text: "The interesting change is subtler." },
    { type: "paragraph", text: "Alcohol may be losing some of its status as the automatic choice." },
    { type: "paragraph", text: "A restaurant can offer a serious zero-proof menu." },
    { type: "paragraph", text: "A friend can order an NA beer without making an announcement." },
    { type: "paragraph", text: "Someone can stop for a month and start again the next." },
    { type: "paragraph", text: "Someone else can stop and realize they don't miss it." },
    { type: "paragraph", text: "Someone can drink Saturday and choose not to drink Sunday." },
    { type: "paragraph", text: "None of those decisions needs to become an identity." },
    { type: "heading", text: "Drinking Less Doesn't Have to Mean Becoming Sober" },
    { type: "paragraph", text: "This may be the part of the trend that interests me most." },
    { type: "paragraph", text: "For a long time, conversations about alcohol tended to become loudest once something had gone wrong." },
    { type: "paragraph", text: "A DUI. A diagnosis. A relationship problem. Dependence. Treatment." },
    { type: "paragraph", text: "Those conversations still matter enormously." },
    { type: "paragraph", text: "But there is another conversation happening earlier." },
    { type: "quote", text: "What if I just don't like what alcohol is doing for me anymore?" },
    { type: "paragraph", text: "That's a different starting point." },
    { type: "paragraph", text: "You don't need a diagnosis to drink less." },
    { type: "paragraph", text: "You don't need a dramatic story." },
    { type: "paragraph", text: "You don't need to promise forever." },
    { type: "paragraph", text: "You don't even need to dislike alcohol." },
    { type: "paragraph", text: "You can simply decide that you'd like less of it in your life." },
    { type: "paragraph", text: "That choice, repeated across millions of people, eventually becomes a statistic." },
    { type: "heading", text: "Maybe Drinking Is Becoming Optional" },
    { type: "paragraph", text: "I don't think the most interesting conclusion from these numbers is that America is becoming sober." },
    { type: "paragraph", text: "It isn't." },
    { type: "paragraph", text: "I think something more realistic is happening." },
    { type: "paragraph", text: "The default is weakening." },
    { type: "paragraph", text: "Alcohol can still be at dinner without being required at dinner." },
    { type: "paragraph", text: "It can still exist at the party without defining the party." },
    { type: "paragraph", text: "Someone can drink without everyone drinking." },
    { type: "paragraph", text: "Someone can stop without everyone asking why." },
    { type: "paragraph", text: "Someone can choose an alcohol-free beer without making a statement." },
    { type: "paragraph", text: "And somebody who has spent years assuming they'll always have wine with dinner might suddenly wonder what happens if they don't." },
    { type: "quote", text: "Maybe the biggest change isn't that America is becoming sober. Maybe drinking is slowly becoming optional." },
    { type: "paragraph", text: "If that's where we're headed, I think that's a pretty interesting place to go." },
    { type: "image", src: "/images/blog/drinking-alcohol-becoming-optional.png", alt: "Friends relaxing around an outdoor fire at sunset with a mix of colorful drinks while a Golden Retriever rests nearby.", caption: "The cultural shift does not require alcohol to disappear. It only requires alcohol to stop being mandatory." },
    { type: "heading", text: "Frequently Asked Questions" },
    { type: "faq", question: "Are Americans actually drinking less alcohol?", answer: "Yes. Multiple recent datasets point in that direction. The 2025 National Survey on Drug Use and Health found declines in past-month alcohol use, binge drinking and heavy alcohol use compared with 2021. Gallup also reports that the share of U.S. adults who say they drink is tied at the lowest level in its polling history." },
    { type: "faq", question: "What percentage of Americans drink alcohol?", answer: "Gallup's 2026 survey found that 54% of U.S. adults say they drink alcohol. The 2025 federal NSDUH found that 44.4% of people age 12 and older used alcohol during the previous month. The surveys measure different populations and questions, so the percentages should not be treated as contradictory." },
    { type: "faq", question: "Is Gen Z drinking less alcohol?", answer: "Younger people are part of the decline, although they are not an alcohol-free generation. Among adults ages 18 to 25, past-month drinking fell from 50.9% in 2021 to 46.2% in 2025, while past-month binge drinking fell from 30.0% to 26.7%." },
    { type: "faq", question: "Is binge drinking declining in the United States?", answer: "Yes. Among Americans age 12 and older, past-month binge drinking declined from 21.7% in 2021 to 19.5% in 2025. Heavy alcohol use also showed a significant decline over the 2021-to-2025 period." },
    { type: "faq", question: "Are alcohol-free drinks becoming more popular?", answer: "Gallup found that 17% of U.S. adults had consumed a nonalcoholic beer, wine or spirit instead of an alcoholic drink during the previous year. Among drinkers who use nonalcoholic alternatives, 38% said they were consuming more of them than they used to, compared with 17% who said they were consuming less." },
    { type: "faq", question: "Does drinking less mean someone has to be sober?", answer: "No. People reduce alcohol in many ways, including drinking fewer days, having fewer drinks, taking temporary breaks, alternating alcoholic and alcohol-free drinks, or stopping entirely. A person does not need to adopt a sober identity in order to drink less." },

    { type: "featureCallout", title: "Your Pattern Matters More Than the National Average", text: "National trends can tell us where drinking culture may be heading. Nova Patterns helps you see something more personal: your own alcohol-free days, drinking days and repeated rhythms over time, so you can decide what you want to change.", feature: "Nova Patterns" },
  ],
};

export default areAmericansActuallyDrinkingLess;
