import type { BlogPost } from "@/lib/blog";

const canAnAlcoholFreeBarActuallySurvive: BlogPost = {
  slug: "can-an-alcohol-free-bar-actually-survive",
  title: "Can an Alcohol-Free Bar Actually Survive? One Just Made It Through Year One.",
  shortTitle: "Can an Alcohol-Free Bar Actually Survive?",
  seoTitle: "Can Alcohol-Free Bars Survive? What Soft Bar's First Year Shows",
  seoDescription:
    "Soft Bar just completed its first year. What does that tell us about alcohol-free bars, third places, sober nightlife and where adults socialize without drinking?",
  category: "News & Culture",
  excerpt:
    "An alcohol-free bar just made it through year one. The more interesting question may be what people were really coming there for.",
  publishedAt: "September 11, 2026",
  publishedDate: "2026-09-11",
  publishedTime: "15:05",
  readTime: "11 min read",
  author: "Lyra",
  image: "/images/blog/can-alcohol-free-bars-survive.png",
  heroAlt:
    "A warm alcohol-free social venue glowing at dusk as people arrive, with coffee, zero-proof drinks and late-night community activity visible through the windows.",
  relatedSlugs: [
    "when-you-stop-drinking-where-do-you-go",
    "coffee-raves-sober-nightlife",
    "are-americans-actually-drinking-less",
  ],
  sources: [
    {
      name: "People",
      title:
        "Carl Radke Celebrates 1 Year of Soft Bar and Reflects on What He's Learned",
      url:
        "https://people.com/carl-radke-celebrates-1-year-of-soft-bar-exclusive-12110591",
    },
    {
      name: "Observer",
      title:
        "Inside New York City's New Generation of Alcohol-Free Bars and Social Spaces",
      url:
        "https://observer.com/2026/04/new-york-city-sober-bars-alcohol-free-nightlife/",
    },
    {
      name: "Real Simple",
      title:
        "Wellness Raves Are the New Self-Care Trend",
      url:
        "https://www.realsimple.com/wellness-raves-self-care-trend-12074133",
    },
    {
      name: "NYC for Free",
      title: "Soft Strides Anniversary Run Club",
      url:
        "https://www.nycforfree.co/events/soft-strides-anniversary-run-club",
    },
  ],
  body: [
    { type: "paragraph", text: "A year is not a very long time in the life of a business." },
    { type: "paragraph", text: "But for an idea plenty of people weren't convinced would work at all, it means something." },
    { type: "paragraph", text: "In September 2025, Carl Radke opened Soft Bar in Brooklyn." },
    { type: "paragraph", text: "There was no vodka." },
    { type: "paragraph", text: "No tequila." },
    { type: "paragraph", text: "No beer with alcohol in it." },
    { type: "paragraph", text: "The idea was to build something that looked and felt like a place adults might actually want to spend time, just without alcohol being at the center of it." },
    { type: "paragraph", text: "This month, Soft Bar celebrated its first anniversary." },
    { type: "paragraph", text: "It survived." },
    { type: "paragraph", text: "More interestingly, it seems to have discovered what people were actually coming there for." },
    { type: "paragraph", text: "And it may not have been the drinks." },
    { type: "quote", text: "Maybe alcohol-free bars aren't solving a drinking problem. Maybe they're solving a somewhere-to-go problem." },

    { type: "heading", text: "First, This Isn't Really a Story About a Reality Star" },
    { type: "paragraph", text: "Carl Radke is known from Summer House, and his own sobriety was part of the reason Soft Bar exists." },
    { type: "paragraph", text: "That makes him the obvious headline." },
    { type: "paragraph", text: "But I think focusing entirely on him misses the more interesting experiment happening inside the building." },
    { type: "paragraph", text: "When Radke was developing Soft Bar, he repeatedly pushed back against calling it a sober bar." },
    { type: "paragraph", text: "He wanted sober people there." },
    { type: "paragraph", text: "But also sober-curious people." },
    { type: "paragraph", text: "People interested in wellness." },
    { type: "paragraph", text: "Pregnant women." },
    { type: "paragraph", text: "People who simply didn't want alcohol that day." },
    { type: "paragraph", text: "In other words: everyone." },
    { type: "paragraph", text: "A year later, that's increasingly what the customer base appears to look like." },
    { type: "paragraph", text: "And that matters because it challenges one of the biggest assumptions surrounding alcohol-free businesses." },
    { type: "paragraph", text: "That you need a large population of permanently sober people nearby to keep one alive." },
    { type: "paragraph", text: "Maybe you don't." },

    { type: "heading", text: "What Happened During Year One?" },
    { type: "paragraph", text: "Soft Bar didn't simply open its doors and spend twelve months serving elaborate mocktails." },
    { type: "paragraph", text: "It became a run club." },
    { type: "paragraph", text: "A game-night venue." },
    { type: "paragraph", text: "A DJ space." },
    { type: "paragraph", text: "A place for conversations about sobriety and mental health." },
    { type: "paragraph", text: "A meeting place for a moms group." },
    { type: "paragraph", text: "A gathering place for a Brooklyn stroller club for dads." },
    { type: "paragraph", text: "It even became a weekly Summer House watch-party venue after staff experimented with programming on slower Tuesday nights. Attendance grew enough that Radke says the bar eventually needed projectors because the existing television couldn't accommodate the crowd." },
    { type: "paragraph", text: "Think about that for a second." },
    { type: "paragraph", text: "None of those things fundamentally requires an alcohol-free cocktail." },
    { type: "paragraph", text: "They require a place." },
    { type: "paragraph", text: "The drinks help pay for the place." },
    { type: "paragraph", text: "But community may be what makes somebody return." },
    { type: "quote", text: "The product might be in the glass. The reason people come back may be sitting around it." },

    { type: "image", src: "/images/blog/alcohol-free-bar-community-third-place.png", alt: "A lively alcohol-free lounge hosting a community game night with adults talking, playing cards and gathering around shared tables.", caption: "The drink may get someone through the door. Community may be what gives them a reason to come back." },

    { type: "heading", text: "We May Have Combined Two Different Needs" },
    { type: "paragraph", text: "For a very long time, adult social life bundled two things together:" },
    { type: "quote", text: "I want a drink." },
    { type: "paragraph", text: "and" },
    { type: "quote", text: "I want somewhere to go." },
    { type: "paragraph", text: "Bars solved both." },
    { type: "paragraph", text: "You didn't need a reservation." },
    { type: "paragraph", text: "You didn't necessarily need dinner." },
    { type: "paragraph", text: "You could arrive at 8:30." },
    { type: "paragraph", text: "You could meet somebody there." },
    { type: "paragraph", text: "You could stay for an hour." },
    { type: "paragraph", text: "You could stay for three." },
    { type: "paragraph", text: "There were other adults around." },
    { type: "paragraph", text: "There was music." },
    { type: "paragraph", text: "There was energy." },
    { type: "paragraph", text: "Nobody wondered why you weren't home." },
    { type: "paragraph", text: "Alcohol happened to be the economic engine underneath much of it." },
    { type: "paragraph", text: "So when somebody stops drinking, we tend to think the solution is simple: remove the alcohol." },
    { type: "paragraph", text: "But sometimes we accidentally remove the place too." },

    { type: "heading", text: "Where Exactly Are Adults Supposed to Go?" },
    { type: "paragraph", text: "Think about the alternatives." },
    { type: "paragraph", text: "Coffee shops are wonderful." },
    { type: "paragraph", text: "Many close early." },
    { type: "paragraph", text: "Restaurants are social." },
    { type: "paragraph", text: "They generally expect you to eat." },
    { type: "paragraph", text: "Gyms provide community." },
    { type: "paragraph", text: "But there's an activity attached." },
    { type: "paragraph", text: "Movie theaters are open late." },
    { type: "paragraph", text: "You're supposed to sit quietly and stare forward." },
    { type: "paragraph", text: "Your friend's house is great." },
    { type: "paragraph", text: "Someone has to host." },
    { type: "paragraph", text: "A traditional bar is one of the few adult spaces where the activity can simply be: being there." },
    { type: "paragraph", text: "That's a surprisingly valuable thing." },
    { type: "paragraph", text: "And it's one reason the idea of a third place keeps showing up in conversations about alcohol-free nightlife." },
    { type: "paragraph", text: "Home is one place." },
    { type: "paragraph", text: "Work is another." },
    { type: "paragraph", text: "The third place is somewhere you can simply exist around other people." },
    { type: "paragraph", text: "Radke now describes Soft Bar in essentially those terms." },

    { type: "heading", text: "One Morning at the Bar Explains the Idea Better Than Any Business Plan" },
    { type: "paragraph", text: "On the morning of Soft Bar's anniversary celebration, Radke noticed two pregnant women sitting at the bar having nonalcoholic drinks." },
    { type: "paragraph", text: "One was there with her husband." },
    { type: "paragraph", text: "According to Radke, the husband thanked him because going out together during his wife's pregnancy had started to feel awkward and they hadn't found many places where she felt naturally included." },
    { type: "paragraph", text: "That example stuck with me." },
    { type: "paragraph", text: "Neither customer needed a sobriety program." },
    { type: "paragraph", text: "They needed somewhere to go where the person not drinking wasn't the unusual person at the table." },
    { type: "paragraph", text: "That's an entirely different market." },
    { type: "paragraph", text: "Think about who else fits inside it." },
    { type: "list", items: ["Someone taking medication.", "Someone driving.", "Someone training tomorrow morning.", "Someone doing a month without alcohol.", "Someone who drank yesterday and doesn't want to today.", "Someone four years sober.", "Someone who has never liked alcohol.", "Someone who's tired of waking up at 3 a.m.", "Someone who simply wants a good drink that doesn't contain alcohol."] },
    { type: "paragraph", text: "Those people have very different relationships with drinking." },
    { type: "paragraph", text: "For one evening, they can want the same thing." },

    { type: "heading", text: "This Isn't Only Happening at Soft Bar" },
    { type: "paragraph", text: "That's what makes this more interesting than one Brooklyn business." },
    { type: "paragraph", text: "Other New York operators have been building variations on the same idea." },
    { type: "paragraph", text: "No More Cafe combines nonalcoholic cocktails and coffee." },
    { type: "paragraph", text: "Mockingbird has emphasized an adult entertainment and meeting-space atmosphere without alcohol at the center." },
    { type: "paragraph", text: "Operators interviewed earlier this year described demand for both lower-alcohol lifestyles and social spaces themselves." },
    { type: "paragraph", text: "There are also alcohol-free bottle shops, pop-ups, lounges and event concepts." },
    { type: "paragraph", text: "Not every one will survive." },
    { type: "paragraph", text: "Some won't." },
    { type: "paragraph", text: "That's normal." },
    { type: "paragraph", text: "Traditional restaurants and bars close too." },
    { type: "paragraph", text: "The relevant question isn't whether every sober bar works." },
    { type: "paragraph", text: "It's whether there's enough demand for some version of adult social life without mandatory alcohol to become a sustainable category." },
    { type: "paragraph", text: "A year at Soft Bar doesn't answer that." },
    { type: "paragraph", text: "But it moves the experiment forward." },

    { type: "heading", text: "The Business Model Is Still the Hard Part" },
    { type: "paragraph", text: "This is where we shouldn't get carried away." },
    { type: "paragraph", text: "Soft Bar surviving its first year does not prove alcohol-free bars are easy businesses." },
    { type: "paragraph", text: "Radke says staffing has been one of the biggest challenges." },
    { type: "paragraph", text: "Customer behavior is different." },
    { type: "paragraph", text: "Tipping can be different." },
    { type: "paragraph", text: "Drink consumption is different." },
    { type: "paragraph", text: "And that gets directly to the economic problem." },
    { type: "paragraph", text: "A traditional bar can sell several high-margin alcoholic drinks to one customer over the course of an evening." },
    { type: "paragraph", text: "An alcohol-free venue needs to create enough value that customers come in, stay, order again, return, bring friends, attend events and view the space as somewhere worth spending money." },
    { type: "paragraph", text: "That's harder than making a good mocktail." },
    { type: "quote", text: "An alcohol-free bar still has to be a good bar." },
    { type: "paragraph", text: "Maybe even more so." },
    { type: "list", items: ["The room matters.", "The music matters.", "The service matters.", "The menu matters.", "The events matter.", "The people matter."] },
    { type: "paragraph", text: "Removing alcohol isn't a business model." },
    { type: "paragraph", text: "What you build in its place is." },

    { type: "heading", text: "The Drinks Still Have to Be Good" },
    { type: "paragraph", text: "There's another trap alcohol-free venues have to avoid." },
    { type: "paragraph", text: "Nobody wants to pay cocktail prices for cranberry juice with rosemary sticking out of it." },
    { type: "paragraph", text: "If this category is going to grow, the drinks have to feel intentional." },
    { type: "paragraph", text: "Soft Bar rotates its menu seasonally and has added food since opening. Radke says its Golden Hour remains a bestseller, while the venue continues experimenting with new functional and alcohol-free drinks." },
    { type: "paragraph", text: "That's important." },
    { type: "paragraph", text: "For years, not drinking at a bar often meant choosing among water, club soda, Diet Coke or something very sweet somebody invented thirty seconds after you asked." },
    { type: "paragraph", text: "That experience quietly communicated: the bar wasn't designed for you." },
    { type: "paragraph", text: "Modern alcohol-free menus increasingly communicate something different: we expected you." },
    { type: "paragraph", text: "That's a meaningful change." },

    { type: "heading", text: "But Maybe Events Are the Secret" },
    { type: "paragraph", text: "The more I look at Soft Bar's first year, the more I wonder whether calling these places bars undersells what might make them work." },
    { type: "list", items: ["Run clubs.", "DJ nights.", "Watch parties.", "Panels.", "Game nights.", "Parents' groups.", "Podcast events."] },
    { type: "paragraph", text: "Those aren't beverage strategies." },
    { type: "paragraph", text: "They're programming." },
    { type: "paragraph", text: "Soft Bar's anniversary itself began with a community run and continued with a DJ and celebration back at the venue." },
    { type: "paragraph", text: "Meanwhile, wellness raves and morning dance events are attracting people around music, movement and social connection without requiring traditional nightlife or alcohol." },
    { type: "paragraph", text: "Maybe the successful alcohol-free venue isn't simply: a bar minus alcohol." },
    { type: "paragraph", text: "Maybe it's: a social club plus drinks." },
    { type: "paragraph", text: "That's a much more interesting business." },

    { type: "image", src: "/images/blog/alcohol-free-social-spaces-run-club.png", alt: "A community run club gathering outside an alcohol-free cafe and social venue on a bright weekend morning.", caption: "The same space can serve nightlife at 9 p.m. and community at 9 a.m. That versatility may matter as much as the drink menu." },

    { type: "heading", text: "This Is the Same Change We Keep Seeing Everywhere" },
    { type: "paragraph", text: "This week's Nova stories have accidentally started talking to each other." },
    { type: "paragraph", text: "We looked at national data showing Americans are drinking less." },
    { type: "paragraph", text: "Then we looked at Gen Z and discovered the story isn't simply that young people don't drink." },
    { type: "paragraph", text: "Some drink." },
    { type: "paragraph", text: "Some drink more frequently." },
    { type: "paragraph", text: "Some also consume NA products." },
    { type: "paragraph", text: "The categories overlap." },
    { type: "paragraph", text: "Now we're looking at physical spaces responding to that behavior." },
    { type: "paragraph", text: "This is what cultural change tends to look like." },
    { type: "paragraph", text: "First the consumer changes." },
    { type: "paragraph", text: "Then the products change." },
    { type: "paragraph", text: "Then the places change." },
    { type: "paragraph", text: "Eventually the behavior stops looking unusual." },
    { type: "quote", text: "The most important thing an alcohol-free bar may normalize isn't the drink. It's being out without one." },

    { type: "continueReading", text: "If removing alcohol changes where you spend your time, the bigger question becomes where adult social life goes next.", slug: "when-you-stop-drinking-where-do-you-go" },

    { type: "heading", text: "Traditional Bars Aren't Going Anywhere" },
    { type: "paragraph", text: "Nor should they." },
    { type: "paragraph", text: "This isn't a story about replacing every neighborhood pub with a wellness cafe." },
    { type: "paragraph", text: "Millions of people enjoy drinking." },
    { type: "paragraph", text: "Bars provide community too." },
    { type: "paragraph", text: "Restaurants will continue serving wine." },
    { type: "paragraph", text: "People will continue ordering cocktails." },
    { type: "paragraph", text: "That's not the interesting part." },
    { type: "paragraph", text: "The interesting part is whether adults can have more than one kind of place." },
    { type: "list", items: ["A traditional bar.", "A restaurant.", "A coffee shop.", "An alcohol-free lounge.", "A daytime dance event.", "A late-night cafe.", "A social club.", "A place that serves both alcohol and serious NA drinks."] },
    { type: "paragraph", text: "More options don't require the old ones to disappear." },

    { type: "image", src: "/images/blog/where-to-socialize-without-alcohol.png", alt: "A walkable city block at night with a traditional bar, restaurant, cafe and alcohol-free social club all open side by side.", caption: "The future may not be fewer social spaces. It may simply be more kinds of them." },

    { type: "heading", text: "And Maybe That's Why Sober Bar Is the Wrong Name" },
    { type: "paragraph", text: "I understand why Radke resisted it." },
    { type: "paragraph", text: "Sober bar makes the customer's identity the defining feature of the business." },
    { type: "paragraph", text: "It suggests: this is where sober people go." },
    { type: "paragraph", text: "But a good third place shouldn't require you to explain yourself before walking through the door." },
    { type: "paragraph", text: "Maybe you are sober." },
    { type: "paragraph", text: "Maybe you're sober curious." },
    { type: "paragraph", text: "Maybe you're pregnant." },
    { type: "paragraph", text: "Maybe you're driving." },
    { type: "paragraph", text: "Maybe you're drinking less." },
    { type: "paragraph", text: "Maybe you have absolutely no philosophical position on alcohol whatsoever." },
    { type: "paragraph", text: "You just wanted somewhere interesting to go tonight." },
    { type: "paragraph", text: "That is a much larger idea." },

    { type: "heading", text: "Could This Work Outside Brooklyn?" },
    { type: "paragraph", text: "That's the next real test." },
    { type: "paragraph", text: "Brooklyn has population density." },
    { type: "paragraph", text: "Tourism." },
    { type: "paragraph", text: "Media attention." },
    { type: "paragraph", text: "A large wellness culture." },
    { type: "paragraph", text: "A celebrity founder certainly doesn't hurt." },
    { type: "paragraph", text: "So we should be careful about assuming Soft Bar can simply be copied into every American suburb." },
    { type: "paragraph", text: "Radke himself appears to understand that." },
    { type: "paragraph", text: "He says he'd like to eventually expand to another city and has discussed possibilities including canned NA drinks and locations or licensing opportunities in airports, hotels and casinos." },
    { type: "paragraph", text: "But he also says he wants to move slowly and learn from the first location before expanding." },
    { type: "paragraph", text: "That's sensible." },
    { type: "paragraph", text: "One year proves survival." },
    { type: "paragraph", text: "It doesn't prove scalability." },
    { type: "paragraph", text: "Those are very different milestones." },

    { type: "heading", text: "Airports Might Actually Make a Lot of Sense" },
    { type: "paragraph", text: "This part caught my attention." },
    { type: "paragraph", text: "Think about an airport." },
    { type: "paragraph", text: "People are killing time." },
    { type: "paragraph", text: "They're traveling alone." },
    { type: "paragraph", text: "They're meeting colleagues." },
    { type: "paragraph", text: "They're anxious." },
    { type: "paragraph", text: "They're tired." },
    { type: "paragraph", text: "They're working." },
    { type: "paragraph", text: "They're driving when they land." },
    { type: "paragraph", text: "Some don't want to drink before a flight." },
    { type: "paragraph", text: "And yet airport social space has traditionally leaned heavily on restaurants and bars." },
    { type: "paragraph", text: "An alcohol-free lounge with good coffee, NA cocktails, food, charging, comfortable seating and some atmosphere?" },
    { type: "paragraph", text: "That doesn't sound particularly niche." },
    { type: "paragraph", text: "Neither does a hotel version." },
    { type: "paragraph", text: "Again, the interesting business may not be a place for sober people." },
    { type: "paragraph", text: "It may simply be a better place to spend an hour." },

    { type: "heading", text: "One Year Isn't Proof. But It Is Evidence." },
    { type: "paragraph", text: "Soft Bar hasn't proven the alcohol-free bar model." },
    { type: "paragraph", text: "We shouldn't pretend it has." },
    { type: "paragraph", text: "We don't have its financial statements." },
    { type: "paragraph", text: "We don't know its profitability." },
    { type: "paragraph", text: "We don't know what happens in year two, year five or during an economic downturn." },
    { type: "paragraph", text: "Survival alone isn't the same thing as a healthy business." },
    { type: "paragraph", text: "But something did happen during that first year." },
    { type: "paragraph", text: "People came." },
    { type: "paragraph", text: "Some came back." },
    { type: "paragraph", text: "Groups formed." },
    { type: "paragraph", text: "Events filled." },
    { type: "paragraph", text: "The business adjusted." },
    { type: "paragraph", text: "The space became useful to people its founder hadn't necessarily designed a separate category for." },
    { type: "paragraph", text: "And one year later, the doors are still open." },
    { type: "paragraph", text: "For an idea that many people once treated like a punchline, that's worth noticing." },

    { type: "heading", text: "Maybe We Were Asking the Wrong Question" },
    { type: "paragraph", text: "When alcohol-free bars started appearing, the obvious question was: will sober people actually go to a bar?" },
    { type: "paragraph", text: "Maybe that was never the right question." },
    { type: "paragraph", text: "The better question might be: do adults still want somewhere to go when they don't want alcohol?" },
    { type: "paragraph", text: "That answer seems much easier." },
    { type: "paragraph", text: "Of course they do." },
    { type: "list", items: ["They still want music.", "They still want conversation.", "They still want to meet somebody after work.", "They still want a first date.", "They still want to watch the game.", "They still want to celebrate.", "They still want to leave the house on a Friday night."] },
    { type: "paragraph", text: "Removing alcohol doesn't remove any of that." },
    { type: "quote", text: "Sometimes what you were looking for wasn't the drink. It was somewhere to go." },
    { type: "paragraph", text: "And if businesses can figure out how to build around that, Soft Bar's first birthday may eventually look less like an unusual milestone and more like an early sign of what adult social life was becoming." },

    { type: "heading", text: "Frequently Asked Questions" },
    { type: "faq", question: "What is an alcohol-free bar?", answer: "An alcohol-free bar is a social venue that serves drinks without alcohol, often including zero-proof cocktails, nonalcoholic beer, coffee, functional beverages and food. Some operate more like lounges, cafes or social clubs than traditional bars." },
    { type: "faq", question: "Are sober bars actually popular?", answer: "Interest is growing, but the category is still relatively young. Soft Bar in Brooklyn has completed its first year while other alcohol-free lounges, cafes and social clubs have opened in cities including New York. One successful year does not prove every alcohol-free bar will work, but it shows there is real demand for some versions of the concept." },
    { type: "faq", question: "Do you have to be sober to go to an alcohol-free bar?", answer: "No. Alcohol-free venues can attract sober people, sober-curious customers, designated drivers, pregnant customers, people taking a break from alcohol and people who simply do not want to drink that night." },
    { type: "faq", question: "How do alcohol-free bars make money?", answer: "They still need to operate like hospitality businesses, earning revenue through drinks, food, events, repeat visits and community programming. Without alcohol's traditional margins, atmosphere, service, programming and customer loyalty may become even more important." },
    { type: "faq", question: "What is a third place?", answer: "A third place is a social environment outside home and work where people can gather informally. Coffee shops, neighborhood bars, cafes, libraries and social clubs can all function as third places." },
    { type: "faq", question: "Where can adults socialize without drinking?", answer: "Options can include alcohol-free bars, late-night cafes, coffee shops, restaurants with strong zero-proof menus, run clubs, game nights, music events, social clubs, wellness events and community gatherings where alcohol is not the central activity." },

    { type: "featureCallout", title: "You Don't Have to Stop Going Out", text: "Nova Situations was built for the moments when social life and alcohol overlap. Whether you're sober, cutting back or simply not drinking tonight, Nova can help you think through restaurants, parties, weddings and other situations without making staying home the only option.", feature: "Nova Situations" },
  ],
};

export default canAnAlcoholFreeBarActuallySurvive;
