import type { BlogPost } from "@/lib/blog";

const isGenZReallyDrinkingLess: BlogPost = {
  slug: "is-gen-z-really-drinking-less",
  title: "Is Gen Z Really Drinking Less? It's More Complicated Than That.",
  shortTitle: "Is Gen Z Really Drinking Less?",
  seoTitle: "Is Gen Z Drinking Less Alcohol? What the Latest Data Actually Shows",
  seoDescription:
    "Gen Z is drinking less by some measures and more often by others. Here is what federal data, Morning Consult and alcohol-free trends actually show.",
  category: "News & Culture",
  excerpt:
    "Gen Z has been called the sober generation. New data complicates that story. Fewer young adults may drink overall, while some who do drink are doing it more often.",
  publishedAt: "September 10, 2026",
  publishedDate: "2026-09-10",
  publishedTime: "01:10",
  readTime: "11 min read",
  author: "Lyra",
  image: "/images/blog/is-gen-z-really-drinking-less.png",
  heroAlt:
    "A diverse group of young adults walking through a lively nightlife district at dusk with bars, coffee shops and zero-proof options around them.",
  relatedSlugs: [
    "are-americans-actually-drinking-less",
    "are-people-drinking-less-alcohol",
    "do-alcohol-free-drinks-help-you-drink-less",
  ],
  sources: [
    {
      name: "Morning Consult",
      title: "Gen Z Is Drinking More, but the Sober-Curious Story Isn't Over",
      url: "https://morningconsult.com/articles/gen-z-drinking-trends-sober",
    },
    {
      name: "SAMHSA",
      title:
        "Key Substance Use and Mental Health Indicators in the United States: Results from the 2025 National Survey on Drug Use and Health",
      url:
        "https://www.samhsa.gov/data/sites/default/files/reports/rpt57150/2025-nsduh-annual-national-html/2025-nsduh-annual-national.htm",
    },
    {
      name: "Gallup",
      title: "Americans' Drinking Remains at Record Low",
      url:
        "https://news.gallup.com/poll/713534/americans-drinking-remains-record-low.aspx",
    },
    {
      name: "Food & Wine",
      title: "Gen Z Is Changing the Way America Drinks",
      url:
        "https://www.foodandwine.com/gen-z-canned-cocktail-trend-12111867",
    },
  ],
  body: [
    { type: "paragraph", text: "For the last few years, Gen Z has been given a pretty simple reputation." },
    { type: "paragraph", text: "They don't drink." },
    { type: "paragraph", text: "They go to run clubs." },
    { type: "paragraph", text: "They order mocktails." },
    { type: "paragraph", text: "They care about sleep." },
    { type: "paragraph", text: "They track everything." },
    { type: "paragraph", text: "They apparently wake up voluntarily on Saturday mornings." },
    { type: "paragraph", text: "And somewhere along the way, an entire generation became known as the generation that was going to kill alcohol." },
    { type: "paragraph", text: "Except something strange is happening." },
    { type: "paragraph", text: "They're drinking more." },
    { type: "paragraph", text: "Or they're drinking less." },
    { type: "paragraph", text: "Depending on which headline you read." },
    { type: "paragraph", text: "And somehow, both can be true." },
    { type: "quote", text: "Gen Z may not be rejecting alcohol. They may be rejecting the idea that drinking has to be all or nothing." },

    { type: "heading", text: "Wait. Didn't We Just Say Young People Are Drinking Less?" },
    { type: "paragraph", text: "Yes." },
    { type: "paragraph", text: "And the national data still says that." },
    { type: "paragraph", text: "The federal National Survey on Drug Use and Health found that among Americans ages 18 to 25, past-month alcohol use declined from 50.9% in 2021 to 46.2% in 2025." },
    { type: "paragraph", text: "Binge drinking declined too, from 30.0% to 26.7%." },
    { type: "paragraph", text: "Heavy alcohol use fell from 7.1% to 6.3%." },
    { type: "paragraph", text: "Those are real declines." },
    { type: "paragraph", text: "We wrote about them earlier this week when we asked whether Americans are actually drinking less." },
    { type: "paragraph", text: "They are." },
    { type: "paragraph", text: "So how do we explain a completely different set of numbers suggesting Gen Z's drinking is going up?" },
    { type: "paragraph", text: "Easy." },
    { type: "paragraph", text: "They're measuring different things." },
    { type: "paragraph", text: "And this is where alcohol statistics get considerably more interesting than the headline." },

    { type: "heading", text: "Morning Consult Found Something Different" },
    { type: "paragraph", text: "Morning Consult has been tracking alcohol behavior among U.S. adults 21 and older across several drinking categories and occasions." },
    { type: "paragraph", text: "When researchers compared late 2024 with mid-2026, Gen Z gained ground in every drinking category and occasion they tracked." },
    { type: "list", items: ["Drinking at bars or restaurants rose.", "Drinking at home rose.", "Beer rose.", "Wine rose slightly.", "Liquor rose.", "Hard seltzer rose.", "Craft beer rose.", "Even low- and no-alcohol beer rose."] },
    { type: "paragraph", text: "The biggest frequency change was going out." },
    { type: "paragraph", text: "In late 2024, about 26% of Gen Z adults said they drank at bars or restaurants weekly or more often." },
    { type: "paragraph", text: "By mid-2026, that was about 32%." },
    { type: "paragraph", text: "Six points in less than two years is worth paying attention to." },
    { type: "paragraph", text: "But it still doesn't mean the federal data was wrong." },

    { type: "image", src: "/images/blog/gen-z-canned-cocktails-rtd-drinks.png", alt: "A cooler filled with fictional canned cocktails, nonalcoholic beer, sparkling water and regular beer at a casual gathering.", caption: "One clue to Gen Z's drinking style is variety. Alcoholic, alcohol-free and everything in between increasingly share the same cooler." },

    { type: "heading", text: "This Is the Difference Between How Many and How Often" },
    { type: "paragraph", text: "Here's the trick." },
    { type: "paragraph", text: "Imagine 100 young adults." },
    { type: "paragraph", text: "Two years ago, 50 of them drank alcohol." },
    { type: "paragraph", text: "Today, maybe roughly the same number drinks." },
    { type: "paragraph", text: "But some of the people who drink now go out twice a week instead of twice a month." },
    { type: "paragraph", text: "You could accurately report: the percentage of young adults who drink hasn't increased." },
    { type: "paragraph", text: "And also: young adults who drink are drinking more frequently." },
    { type: "paragraph", text: "Both statements can describe the same population." },
    { type: "paragraph", text: "Morning Consult actually tested for this." },
    { type: "paragraph", text: "Gen Z is aging. More members of the generation turn 21 every year, while older members move deeper into their twenties, historically a period when alcohol use is relatively common." },
    { type: "paragraph", text: "So researchers compared people at the same age." },
    { type: "paragraph", text: "When they held age constant and looked at 21-to-29-year-olds, most of the increase in the share who drank disappeared." },
    { type: "paragraph", text: "Beer, liquor and bar-drinking incidence were essentially flat." },
    { type: "paragraph", text: "But the frequency increase remained." },
    { type: "paragraph", text: "Weekly-or-more bar drinking among 21-to-29-year-olds rose roughly five percentage points, from about 27% to 32%." },
    { type: "paragraph", text: "Beer and liquor frequency rose around three to four points too." },
    { type: "quote", text: "More young adults aren't necessarily starting to drink. Some of the young adults who already drink appear to be doing it more often." },

    { type: "heading", text: "And Gen Z Still Drinks Less Than Millennials" },
    { type: "paragraph", text: "This part gets lost immediately when the headline says Gen Z is drinking more." },
    { type: "paragraph", text: "They still aren't the heaviest-drinking generation." },
    { type: "paragraph", text: "Morning Consult found millennials lead Gen Z in at-home drinking, liquor, beer, wine, craft beer and most measures of drinking frequency." },
    { type: "paragraph", text: "So Gen Z's trajectory may be moving upward while its overall level remains lower." },
    { type: "paragraph", text: "Think of two runners." },
    { type: "paragraph", text: "One is ahead but standing still." },
    { type: "paragraph", text: "The other is behind but moving toward them." },
    { type: "paragraph", text: "The second runner is gaining." },
    { type: "paragraph", text: "That doesn't mean they're winning the race." },

    { type: "heading", text: "What Gen Z Drinks Is Changing Too" },
    { type: "paragraph", text: "This is where the story gets much more cultural." },
    { type: "paragraph", text: "Gen Z isn't simply discovering Grandpa's liquor cabinet." },
    { type: "paragraph", text: "Their preferences look different." },
    { type: "paragraph", text: "Morning Consult tracks purchase consideration across 171 alcohol brands." },
    { type: "paragraph", text: "Among Gen Z adults, the top two brands in 2026 weren't bottles of liquor." },
    { type: "paragraph", text: "They were ready-to-drink canned cocktails." },
    { type: "paragraph", text: "Jack Daniel's & Coca-Cola ranked first. Bacardi & Coca-Cola ranked second. The regular bottle of Jack Daniel's ranked fourth." },
    { type: "paragraph", text: "That is fascinating." },
    { type: "paragraph", text: "The brand is familiar." },
    { type: "paragraph", text: "The format is different." },
    { type: "list", items: ["One can.", "One serving.", "No cocktail shaker.", "No full bottle sitting around afterward.", "Open it and you're done."] },

    { type: "heading", text: "Why Canned Cocktails Make Sense for This Generation" },
    { type: "paragraph", text: "Convenience is part of it." },
    { type: "paragraph", text: "So is price." },
    { type: "paragraph", text: "So is experimentation." },
    { type: "paragraph", text: "A canned cocktail lets someone try something without buying a bottle of tequila, mixers, citrus, bitters and whatever else TikTok told them they needed." },
    { type: "paragraph", text: "You don't need to know how to make a cocktail." },
    { type: "paragraph", text: "You don't need a home bar." },
    { type: "paragraph", text: "You don't need to commit to an entire bottle." },
    { type: "paragraph", text: "You buy the flavor that sounds interesting. You drink it. Next weekend you try something else." },
    { type: "paragraph", text: "Recent reporting on the Morning Consult findings describes that combination of convenience, affordability and low commitment as particularly attractive to younger consumers." },
    { type: "paragraph", text: "That doesn't necessarily sound like a generation obsessed with alcohol." },
    { type: "paragraph", text: "It sounds like a generation accustomed to choice." },

    { type: "heading", text: "Hard Seltzer Never Really Left Either" },
    { type: "paragraph", text: "If you want one number that demonstrates how differently generations can drink, look at hard seltzer." },
    { type: "paragraph", text: "Morning Consult found 42.8% of Gen Z adults drink hard seltzer, compared with just 17.6% of baby boomers." },
    { type: "paragraph", text: "That's a 25-point generational gap." },
    { type: "paragraph", text: "Gen Z also shows strong interest in tequila and flavored drinks." },
    { type: "paragraph", text: "Again, this isn't necessarily more drinking." },
    { type: "paragraph", text: "It's evidence that when younger adults choose alcohol, they may choose differently." },
    { type: "paragraph", text: "The old beer-versus-wine-versus-whiskey framework doesn't describe the entire market anymore." },

    { type: "heading", text: "Now Here's the Weird Part: They Love NA Beer Too" },
    { type: "paragraph", text: "This is my favorite part of the entire dataset." },
    { type: "paragraph", text: "Because if our cultural categories were correct, this shouldn't make sense." },
    { type: "paragraph", text: "Gen Z's use of low- and no-alcohol beer climbed to 40.8%, tying millennials for the highest adoption of any generation Morning Consult measured." },
    { type: "paragraph", text: "At the same time, Gen Z's regular drinking increased." },
    { type: "paragraph", text: "Read those together." },
    { type: "paragraph", text: "The generation supposedly abandoning alcohol is drinking more frequently." },
    { type: "paragraph", text: "And the generation supposedly returning to alcohol is also embracing alcohol-free beer." },
    { type: "paragraph", text: "So which side are they on?" },
    { type: "paragraph", text: "Apparently neither." },
    { type: "quote", text: "The same person can drink a beer Friday and an NA beer Saturday without experiencing an identity crisis." },

    { type: "image", src: "/images/blog/gen-z-drinking-health-wellness-culture.png", alt: "A diverse group of young adults finishing a waterfront run and meeting for coffee on a bright weekend morning.", caption: "Drinking Friday night and caring about Saturday morning are not mutually exclusive anymore." },

    { type: "heading", text: "Meet the Additive Drinker" },
    { type: "paragraph", text: "Morning Consult describes the alcohol-free behavior as additive rather than substitutive." },
    { type: "paragraph", text: "In other words, many Gen Z consumers don't appear to be replacing alcohol entirely with NA products." },
    { type: "paragraph", text: "They're adding NA products to the collection of things they drink." },
    { type: "list", items: ["Alcohol.", "NA beer.", "Hard seltzer.", "Coffee.", "Energy drinks.", "Sparkling water.", "Whatever comes next."] },
    { type: "paragraph", text: "The beverage doesn't necessarily announce who they are." },
    { type: "paragraph", text: "It solves whatever they want from that particular moment." },
    { type: "paragraph", text: "And there is a term increasingly used for alternating alcohol and alcohol-free drinks during the same occasion: zebra striping." },
    { type: "paragraph", text: "Drink. NA drink. Maybe another drink. Maybe another NA." },
    { type: "paragraph", text: "It's moderation without requiring an announcement that you're moderating." },

    { type: "heading", text: "This Might Explain Why the Sober Generation Story Felt Too Simple" },
    { type: "paragraph", text: "Generational labels are irresistible." },
    { type: "paragraph", text: "Millennials killed napkins. Gen Z killed skinny jeans. Somebody apparently killed chain restaurants." },
    { type: "paragraph", text: "And now Gen Z was going to kill alcohol." },
    { type: "paragraph", text: "Real people are considerably less cooperative." },
    { type: "paragraph", text: "Federal data clearly shows young-adult alcohol use has declined over the last several years." },
    { type: "paragraph", text: "Morning Consult now shows increased drinking frequency among legal-age young adults who drink." },
    { type: "paragraph", text: "Gallup shows overall American drinking remains at a record-low 54%, while 17% of adults report substituting nonalcoholic beer, wine or spirits for alcohol at least sometimes." },
    { type: "paragraph", text: "Those findings don't cancel one another." },
    { type: "paragraph", text: "Together they describe a drinking culture that may simply be becoming more flexible." },

    { type: "continueReading", text: "This story makes more sense next to the broader national trend. We also looked at why Americans appear to be drinking less overall, even as the culture around drinking gets more complicated.", slug: "are-americans-actually-drinking-less" },

    { type: "heading", text: "Maybe the Real Change Is the Default" },
    { type: "paragraph", text: "For older generations, alcohol often came bundled with the activity." },
    { type: "list", items: ["Going to a bar meant drinking.", "Dinner out meant wine.", "Watching football meant beer.", "Celebrating meant champagne.", "Vacation meant cocktails."] },
    { type: "paragraph", text: "You didn't necessarily make a decision about alcohol." },
    { type: "paragraph", text: "The activity made the decision for you." },
    { type: "paragraph", text: "That's the part I think may be changing." },
    { type: "paragraph", text: "A 24-year-old can go to the bar and drink." },
    { type: "paragraph", text: "Then go to a run club the next morning." },
    { type: "paragraph", text: "Then order an NA beer." },
    { type: "paragraph", text: "Then have tequila the following weekend." },
    { type: "paragraph", text: "Then do a month without drinking." },
    { type: "paragraph", text: "None of those decisions has to define the next one." },
    { type: "paragraph", text: "That's not sobriety." },
    { type: "paragraph", text: "It's not necessarily moderation either." },
    { type: "paragraph", text: "It's optionality." },

    { type: "heading", text: "Health Still Matters" },
    { type: "paragraph", text: "None of this means Gen Z suddenly stopped caring about health." },
    { type: "paragraph", text: "National attitudes toward alcohol's health effects have changed dramatically." },
    { type: "paragraph", text: "Gallup found 51% of Americans now believe drinking one or two alcoholic beverages per day is bad for health, up from 27% in 2001." },
    { type: "paragraph", text: "Younger adults have grown up during a period when information about sleep, cancer risk, anxiety, calories, recovery and alcohol is much easier to find." },
    { type: "paragraph", text: "They also live in a world where a watch can tell them exactly what happened to their sleep after three drinks." },
    { type: "paragraph", text: "You don't need a public-health campaign when your wrist tells you at 7:12 tomorrow morning." },
    { type: "paragraph", text: "Knowing alcohol has consequences doesn't automatically mean nobody drinks." },
    { type: "paragraph", text: "It may simply change when drinking feels worth those consequences." },

    { type: "heading", text: "And This Is Why Alcohol-Free Drinks Matter" },
    { type: "paragraph", text: "If you believe alcohol-free drinks are only for people who have quit drinking permanently, Gen Z's behavior makes no sense." },
    { type: "paragraph", text: "If you think of them as another beverage choice, it makes perfect sense." },
    { type: "list", items: ["Maybe you want the first drink, not the second.", "Maybe you're driving later.", "Maybe you have a workout tomorrow.", "Maybe you're staying longer than you expected.", "Maybe you like the taste.", "Maybe you don't want alcohol tonight.", "Maybe you do tomorrow."] },
    { type: "paragraph", text: "That flexibility may be exactly why the alcohol-free category keeps growing alongside drinking rather than only replacing it." },

    { type: "heading", text: "Is That Good or Bad?" },
    { type: "paragraph", text: "Probably neither as a generational judgment." },
    { type: "paragraph", text: "If young adults who already drink are drinking more frequently, that's worth watching." },
    { type: "paragraph", text: "Alcohol-related health risks don't disappear because the drink comes in a beautifully designed can." },
    { type: "paragraph", text: "And binge drinking remains common." },
    { type: "paragraph", text: "In 2025, 26.7% of Americans ages 18 to 25 reported binge drinking in the previous month." },
    { type: "paragraph", text: "That's more than one in four." },
    { type: "paragraph", text: "So we shouldn't turn this into: Gen Z solved drinking." },
    { type: "paragraph", text: "They didn't." },
    { type: "paragraph", text: "We also shouldn't turn it into: Gen Z's sobriety experiment failed." },
    { type: "paragraph", text: "The data doesn't show that either." },

    { type: "heading", text: "Maybe They're Just Drinking Differently" },
    { type: "paragraph", text: "That's the conclusion I keep coming back to." },
    { type: "paragraph", text: "The old question was: Do you drink?" },
    { type: "paragraph", text: "The emerging question may be: When do you drink?" },
    { type: "paragraph", text: "And then: how much?" },
    { type: "paragraph", text: "What?" },
    { type: "paragraph", text: "Where?" },
    { type: "paragraph", text: "Why?" },
    { type: "paragraph", text: "What are you doing tomorrow?" },
    { type: "paragraph", text: "Do you actually want another one?" },
    { type: "paragraph", text: "Would an NA drink work just as well right now?" },
    { type: "paragraph", text: "That's a much more complicated relationship with alcohol." },
    { type: "paragraph", text: "It may also be a more intentional one." },
    { type: "quote", text: "Gen Z may not be rejecting alcohol. They may be rejecting the idea that drinking has to be constant." },

    { type: "image", src: "/images/blog/gen-z-alcohol-and-non-alcoholic-drinks.png", alt: "Young adults at a rooftop gathering with alcoholic and alcohol-free canned drinks, sparkling water and cocktails available together.", caption: "Maybe the clearest cultural shift is simple: both options belong at the same party." },

    { type: "heading", text: "So Is Gen Z Really Drinking Less?" },
    { type: "paragraph", text: "Over the longer term, federal data says young adults are drinking less than they were several years ago." },
    { type: "paragraph", text: "Over the shorter term, Morning Consult says drinking frequency among legal-age young adults who drink has been rising." },
    { type: "paragraph", text: "Gen Z still drinks less than millennials on most measures." },
    { type: "paragraph", text: "They also lead or nearly lead adoption of some alcohol-free categories." },
    { type: "paragraph", text: "They like canned cocktails." },
    { type: "paragraph", text: "They like hard seltzer." },
    { type: "paragraph", text: "They go to bars." },
    { type: "paragraph", text: "They also drink NA beer." },
    { type: "paragraph", text: "That's not a contradiction." },
    { type: "paragraph", text: "It's a reminder that human behavior rarely fits inside the headline we gave it." },
    { type: "paragraph", text: "Maybe Gen Z isn't the sober generation." },
    { type: "paragraph", text: "Maybe it isn't the drinking generation either." },
    { type: "paragraph", text: "Maybe it's the generation that increasingly expects both options to be there." },
    { type: "paragraph", text: "And honestly? That might be the more interesting change." },

    { type: "heading", text: "Frequently Asked Questions" },
    { type: "faq", question: "Is Gen Z drinking less alcohol?", answer: "Over the longer term, federal data shows declines among young adults. Among Americans ages 18 to 25, past-month drinking fell from 50.9% in 2021 to 46.2% in 2025, while binge drinking also declined. That does not mean every measure of Gen Z drinking is falling." },
    { type: "faq", question: "Is Gen Z drinking more in 2026?", answer: "Morning Consult found that legal-age Gen Z adults who drink are drinking more frequently across several categories and occasions than they were in late 2024. After controlling for age, most increases in the share who drink disappeared, but some frequency increases remained." },
    { type: "faq", question: "Why do Gen Z drinking statistics seem contradictory?", answer: "Different surveys measure different things. Federal data can show fewer young adults drinking in the past month while consumer research simultaneously shows that some legal-age young adults who already drink are doing so more frequently. Both can be true." },
    { type: "faq", question: "What alcohol does Gen Z prefer?", answer: "Morning Consult's 2026 data shows strong Gen Z interest in ready-to-drink canned cocktails, hard seltzer, tequila and flavored drinks. Their preferences differ from older generations and often emphasize convenience, variety and single-serve formats." },
    { type: "faq", question: "Does Gen Z drink nonalcoholic beverages too?", answer: "Yes. Morning Consult found low- and no-alcohol beer use among Gen Z reached 40.8%, tying millennials for the highest adoption among the generations measured. For many younger consumers, alcohol-free drinks appear to be an additional option rather than a complete replacement for alcohol." },
    { type: "faq", question: "What is zebra striping?", answer: "Zebra striping is a term used for alternating alcoholic and alcohol-free drinks during the same social occasion. It reflects a more flexible approach to drinking in which someone may moderate without giving up alcohol entirely." },

    { type: "featureCallout", title: "Your Drinking Doesn't Need a Generational Label", text: "National trends can tell us how culture is changing. Nova helps you focus on your own patterns, whether that means drinking less, taking a break, choosing alcohol-free more often or not drinking at all.", feature: "Nova Patterns" },
  ],
};

export default isGenZReallyDrinkingLess;
