import type { BlogPost } from "@/lib/blog";

const laborDayPartyIActuallyWantToAttend: BlogPost = {
  slug: "the-labor-day-party-i-actually-want-to-attend",
  title: "The Labor Day Party I Actually Want to Attend",
  shortTitle: "The Labor Day Party I Want to Attend",
  seoTitle: "An Easy Labor Day Party the Host Can Actually Enjoy",
  seoDescription: "Danielle shares her relaxed Labor Day entertaining plan, with make-ahead food, self-serve drinks and The September Pour, a pear and apple Pour: Zero.",
  category: "Lifestyle & Entertaining",
  excerpt: "Good food, a relaxed table, self-serve drinks and almost nothing left to do once everyone arrives. Danielle plans the Labor Day party she actually wants to attend.",
  publishedAt: "September 5, 2026",
  publishedDate: "2026-09-05",
  publishedTime: "09:00",
  readTime: "8 min read",
  author: "Danielle",
  image: "/images/blog/labor-day-party-entertaining-at-home.png",
  heroAlt: "A relaxed Labor Day backyard table set with late-summer food, hydrangeas and simple linens in warm afternoon light.",
  relatedSlugs: ["how-to-host-a-summer-party-when-not-everyone-drinks", "i-didnt-give-up-my-5-oclock-drink", "the-last-dinner-of-summer"],
  sources: [],
  body: [
    { type: "paragraph", text: "I like having people over." },
    { type: "paragraph", text: "What I don't like is realizing halfway through the afternoon that everyone else is at the party and I'm still hosting it." },
    { type: "paragraph", text: "I'm checking the grill." },
    { type: "paragraph", text: "Looking for more ice." },
    { type: "paragraph", text: "Making another drink." },
    { type: "paragraph", text: "Bringing something else outside." },
    { type: "paragraph", text: "Cleaning something nobody asked me to clean." },
    { type: "paragraph", text: "At some point, I have to remind myself why everyone is here in the first place." },
    { type: "paragraph", text: "I wanted to spend time with them." },
    { type: "paragraph", text: "So if I were planning Labor Day exactly the way I want it this year, I'd start with one rule:" },
    { type: "quote", text: "Once everyone arrives, I want to sit down too." },
    { type: "paragraph", text: "That one decision changes almost everything about how I'd plan the party." },
    { type: "heading", text: "I Don't Need Seven Things Coming Off the Grill" },
    { type: "paragraph", text: "I love good food." },
    { type: "paragraph", text: "I just don't think good food requires spending the entire afternoon standing over it." },
    { type: "paragraph", text: "For Labor Day, I'd rather choose one thing that actually needs attention on the grill and make everything else as easy as possible before anyone arrives." },
    { type: "paragraph", text: "Burgers. Chicken. Sausages. Whatever sounds good and doesn't require me to remember six different cooking times." },
    { type: "paragraph", text: "Then I'd build the rest of the table around things that are perfectly happy waiting for us." },
    { type: "list", items: ["A big tomato salad", "Corn", "Pasta salad or potato salad", "Watermelon", "Good bread", "Chips and something to dip them in", "Peaches if they still look good at the market"] },
    { type: "paragraph", text: "Nothing particularly groundbreaking." },
    { type: "paragraph", text: "That's kind of the point." },
    { type: "paragraph", text: "I don't want someone walking into the backyard and thinking: Wow, she must have worked on this for nine hours." },
    { type: "paragraph", text: "I'd rather they grab a plate and sit down." },
    { type: "quote", text: "If the food requires me to miss the party, I planned too much food." },
    { type: "heading", text: "I Want the Table to Look Good Before People Touch It" },
    { type: "paragraph", text: "I like a beautiful table." },
    { type: "paragraph", text: "I also think sometimes we put so much effort into making a table look perfect that we forget what it's actually for." },
    { type: "paragraph", text: "People are going to move the chairs. Someone will put their phone next to the flowers. A serving spoon will end up in the wrong bowl. Napkins will get unfolded. Glasses will leave rings. The food will disappear." },
    { type: "paragraph", text: "Hopefully someone spills something because they're laughing." },
    { type: "paragraph", text: "That's the good part." },
    { type: "paragraph", text: "For Labor Day, I'd keep the table somewhere between summer and fall." },
    { type: "paragraph", text: "I'm not ready for pumpkins." },
    { type: "paragraph", text: "I'm not ready for everything to be orange." },
    { type: "paragraph", text: "It's still summer enough for hydrangeas, tomatoes, peaches and whatever is growing outside." },
    { type: "paragraph", text: "But September is here." },
    { type: "paragraph", text: "So I'd use simple linen napkins, a few branches or flowers, maybe pears and apples mixed into the table, and whatever glassware I already own." },
    { type: "paragraph", text: "No theme. No centerpiece that prevents people from seeing each other. Nothing I'm afraid someone will touch." },
    { type: "quote", text: "The table isn't finished when it looks perfect. It's finished when people start messing it up." },
    { type: "heading", text: "I'm Done Making Everyone a Drink" },
    { type: "paragraph", text: "This might be the biggest change I'd make." },
    { type: "paragraph", text: "I don't want to spend Labor Day asking what I can get everyone, whether someone wants another drink, where I put the opener, or who needs more ice." },
    { type: "paragraph", text: "I want one place where everything is available." },
    { type: "paragraph", text: "Ice. Sparkling water. Still water. Iced tea. Citrus. Whatever alcoholic drinks we're serving." },
    { type: "paragraph", text: "And something alcohol-free that feels like it belongs there because it's good, not because somebody needed a special sober option." },
    { type: "paragraph", text: "Then everybody can decide what they want." },
    { type: "paragraph", text: "No separate alcohol-free table. No announcement. No explaining. Just drinks." },
    { type: "paragraph", text: "My feelings around that have changed more than I expected over the last few weeks." },
    { type: "paragraph", text: "When I first started changing what I drank, I was mostly thinking about what I could have instead of wine." },
    { type: "paragraph", text: "Now I'm starting to think less about replacement and more about what actually sounds good." },
    { type: "paragraph", text: "That's much more fun." },
    { type: "image", src: "/images/blog/labor-day-self-serve-drink-station.png", alt: "A self-serve Labor Day drink station with ice, water, iced tea, alcohol-free choices, wine, citrus, herbs and a pitcher of The September Pour.", caption: "Put the choices in one place, make them easy to understand, and let everyone pour what they actually want." },
    { type: "heading", text: "The September Pour" },
    { type: "subheading", text: "A Pear, Apple, Rosemary & Ginger Pour: Zero" },
    { type: "paragraph", text: "I wanted this one to feel like September without pretending it's already October." },
    { type: "paragraph", text: "Apple makes sense. Pear makes it softer. Ginger gives it a little bite. Rosemary makes the whole thing smell like the season is changing." },
    { type: "paragraph", text: "But it's still cold, bright and sparkling because September is not sweater weather every day just because the calendar says fall is coming." },
    { type: "quote", text: "I don't need my drink to taste like fall exploded in a glass. I just want it to know September arrived." },
    { type: "image", src: "/images/blog/september-pour-pear-apple-rosemary.png", alt: "The September Pour, a sparkling pear, apple, rosemary and ginger alcohol-free drink over ice beside fresh orchard ingredients.", caption: "The September Pour is crisp, lightly orchard-sweet and just fall enough for the first weekend of September." },
    { type: "subheading", text: "What You'll Need" },
    { type: "paragraph", text: "For one drink:" },
    { type: "list", items: ["2 ounces chilled pear nectar", "1 ounce chilled apple cider", "1/2 ounce fresh lemon juice", "1/4 ounce rosemary-honey syrup", "2 to 3 ounces chilled sparkling water", "Ice", "A thin pear slice, apple slice or small rosemary sprig for garnish, optional"] },
    { type: "subheading", text: "For the Rosemary-Honey Syrup" },
    { type: "paragraph", text: "You don't need to make a complicated syrup for one drink." },
    { type: "paragraph", text: "Combine equal parts honey and warm water and stir until the honey dissolves." },
    { type: "paragraph", text: "Add a small sprig of fresh rosemary and let it steep for about 10 minutes." },
    { type: "paragraph", text: "Remove the rosemary and let the syrup cool." },
    { type: "paragraph", text: "Keep whatever is left in the refrigerator for another drink." },
    { type: "subheading", text: "How to Make It" },
    { type: "paragraph", text: "Fill a glass with ice." },
    { type: "paragraph", text: "Add the pear nectar, apple cider, lemon juice and rosemary-honey syrup." },
    { type: "paragraph", text: "Stir gently. Top with sparkling water. Taste it before you do anything else." },
    { type: "paragraph", text: "If it's too sweet, add a little more lemon or sparkling water." },
    { type: "paragraph", text: "If you want more apple, add another splash of cider." },
    { type: "paragraph", text: "If you want more rosemary, I'd use the garnish rather than adding more syrup. Rosemary can go from interesting to Christmas tree pretty quickly." },
    { type: "paragraph", text: "Finish with a thin pear or apple slice and a small rosemary sprig if you have one." },
    { type: "paragraph", text: "Cold, bubbly, a little tart, a little sweet, and just fall enough." },
    { type: "heading", text: "Make the Pitcher Before Anyone Arrives" },
    { type: "paragraph", text: "For a party, I'm absolutely not making these one at a time." },
    { type: "paragraph", text: "That would defeat the entire point of this article." },
    { type: "paragraph", text: "I'd make the base before anyone gets there." },
    { type: "paragraph", text: "For about six drinks:" },
    { type: "list", items: ["12 ounces pear nectar", "6 ounces apple cider", "3 ounces fresh lemon juice", "1 1/2 ounces rosemary-honey syrup"] },
    { type: "paragraph", text: "Stir everything together in a pitcher and refrigerate it." },
    { type: "paragraph", text: "Then put the pitcher next to ice and chilled sparkling water." },
    { type: "paragraph", text: "People can pour the base over ice and add their own bubbles." },
    { type: "paragraph", text: "That keeps the sparkling water from going flat in the pitcher, and it means I don't have to stand there making drinks." },
    { type: "paragraph", text: "If someone wants to adjust theirs, they can. If someone wants sparkling water instead, great. If someone wants something completely different, also great." },
    { type: "quote", text: "I don't need to decide what everybody else is drinking. I just want the alcohol-free option to be good enough that nobody feels like they got the backup drink." },
    { type: "heading", text: "The Drink Table Should Just Be the Drink Table" },
    { type: "paragraph", text: "I've become more aware lately of how often alcohol-free options are treated like a separate category." },
    { type: "paragraph", text: "There's the wine. There's the beer. There's the cocktails. And then somewhere else there's a can of sparkling water for the person who isn't drinking." },
    { type: "paragraph", text: "I don't really want to host that way." },
    { type: "paragraph", text: "I'd rather put everything together." },
    { type: "paragraph", text: "Make it obvious where the alcohol is so nobody accidentally grabs something they don't want." },
    { type: "paragraph", text: "Make the alcohol-free options equally obvious." },
    { type: "paragraph", text: "Then let adults choose." },
    { type: "paragraph", text: "That feels especially natural to me right now because I'm still figuring out what I want my own relationship with alcohol to look like." },
    { type: "paragraph", text: "I've been choosing not to drink." },
    { type: "paragraph", text: "I'm proud of the stretch I've put together." },
    { type: "paragraph", text: "But I don't need everyone around me to make the same choice for mine to feel good." },
    { type: "paragraph", text: "That has been a nice thing to learn." },
    { type: "continueReading", text: "I recently wrote about how changing what I pour at 5 o'clock helped me keep a familiar ritual while changing my drinking.", slug: "i-didnt-give-up-my-5-oclock-drink" },
    { type: "heading", text: "I Don't Want the Party to Be About Drinking" },
    { type: "paragraph", text: "I also don't want it to be about not drinking." },
    { type: "paragraph", text: "It's Labor Day." },
    { type: "paragraph", text: "People came over to eat. Talk. Listen to music. Sit outside. Watch the kids run around. Tell stories they've probably told before. Stay later than they planned." },
    { type: "paragraph", text: "That's the party." },
    { type: "paragraph", text: "What's in everyone's glass is part of the scene, but it doesn't have to become the plot." },
    { type: "paragraph", text: "A few weeks ago, declining alcohol still felt unusual enough that I noticed myself doing it." },
    { type: "paragraph", text: "It's already starting to feel more normal." },
    { type: "paragraph", text: "Sometimes I choose something else and keep talking." },
    { type: "paragraph", text: "That is exactly how I want the drink table to work too." },
    { type: "paragraph", text: "Choose something. Pour it. Go back to the party." },
    { type: "heading", text: "I Want to Be Done Before the Doorbell Rings" },
    { type: "paragraph", text: "This is probably unrealistic in the most literal sense." },
    { type: "paragraph", text: "Something will always need to be done." },
    { type: "paragraph", text: "But I'd like almost everything important finished before the first person arrives." },
    { type: "paragraph", text: "Food made. Table set. Drink station stocked. Music on. Ice out. Bathroom clean enough that I'm not thinking about it." },
    { type: "paragraph", text: "Then I'm done." },
    { type: "paragraph", text: "Not magazine-photo-shoot done." },
    { type: "paragraph", text: "People-are-coming-over done." },
    { type: "paragraph", text: "There's a difference." },
    { type: "paragraph", text: "Nobody I actually want at my house is going to care that I didn't make homemade hamburger buns." },
    { type: "paragraph", text: "They probably won't remember what flowers were on the table either." },
    { type: "paragraph", text: "They might remember sitting outside until it got dark." },
    { type: "paragraph", text: "That's the part I'm trying to plan for." },
    { type: "heading", text: "The Party Should Look Better at the End" },
    { type: "paragraph", text: "I think the prettiest version of a party might actually be the one nobody photographs." },
    { type: "paragraph", text: "Half-empty bowls. A few abandoned glasses. Someone moved a chair into the grass. The serving platters aren't arranged anymore. The lights are on because the sun went down." },
    { type: "paragraph", text: "There are only three people left at the table because everybody else wandered somewhere else." },
    { type: "paragraph", text: "That's when you know the table did its job." },
    { type: "paragraph", text: "It got used." },
    { type: "paragraph", text: "And if I can be sitting there too instead of inside washing something that absolutely could have waited until tomorrow, even better." },
    { type: "image", src: "/images/blog/labor-day-party-host-enjoying-guests.png", alt: "Friends enjoying a relaxed Labor Day dinner outside after sunset while a red-haired woman with glasses sits at the table with her guests.", caption: "The best sign that the party worked might be that the host is still sitting at the table when the lights come on." },
    { type: "heading", text: "This Is the Labor Day Party I Want" },
    { type: "paragraph", text: "Good food. Nothing too complicated. One thing on the grill." },
    { type: "paragraph", text: "A table that looks beautiful enough." },
    { type: "paragraph", text: "A drink station where everybody can find something they actually want." },
    { type: "paragraph", text: "A pitcher of The September Pour waiting in the refrigerator." },
    { type: "paragraph", text: "Music already playing." },
    { type: "paragraph", text: "And me sitting down." },
    { type: "paragraph", text: "The food doesn't have to be perfect." },
    { type: "paragraph", text: "The table doesn't have to look like a magazine." },
    { type: "paragraph", text: "Nobody needs a custom drink made to order." },
    { type: "paragraph", text: "I invited people over because I wanted to spend time with them." },
    { type: "quote", text: "So this Labor Day, I'm planning the party around being one of the guests." },
    { type: "heading", text: "Frequently Asked Questions" },
    { type: "faq", question: "What is an easy Labor Day menu for entertaining?", answer: "Keep the food simple enough that most of it can be prepared before guests arrive. Choose one main item for the grill, then add make-ahead sides such as tomato salad, corn, pasta or potato salad, watermelon, bread, chips and dip, or seasonal fruit." },
    { type: "faq", question: "How do I set up drinks for guests who drink and guests who don't?", answer: "A self-serve drink area can include clearly identified alcoholic and alcohol-free options together, along with ice, water, sparkling water, citrus and other mixers. Keeping the choices in one place makes it easy for guests to choose what they want without making anyone's drink a special announcement." },
    { type: "faq", question: "What is a good alcohol-free drink for Labor Day?", answer: "The September Pour combines pear nectar, apple cider, fresh lemon, rosemary-honey syrup and sparkling water. It bridges late summer and early fall without being heavy or overly sweet." },
    { type: "faq", question: "Can I make The September Pour ahead of time?", answer: "Yes. Combine the pear nectar, apple cider, lemon juice and rosemary-honey syrup ahead of time and refrigerate the mixture. Keep sparkling water separate and add it to individual glasses when serving so the drink stays bubbly." },
    { type: "faq", question: "How can I actually enjoy a party I'm hosting?", answer: "Do as much as possible before guests arrive, simplify the menu, use self-serve drinks, and decide in advance what does not need to be perfect. The goal is to spend time with the people you invited, not continually produce the party while everyone else enjoys it." },
  ],
};

export default laborDayPartyIActuallyWantToAttend;
