import type { BlogPost } from "@/lib/blog";

const theWeirdestThingAboutBeingFourYearsSober: BlogPost = {
  slug: "the-weirdest-thing-about-being-four-years-sober",
  title: "The Weirdest Thing About Being Four Years Sober? I Don’t Think About Sobriety That Much.",
  shortTitle: "Four Years Sober, and It Got Quiet",
  seoTitle: "What Being Four Years Sober Actually Feels Like",
  seoDescription: "After more than four years without alcohol, Neal reflects on something he never expected: sobriety stopped feeling like something he was actively doing.",
  category: "Real Stories & Perspective",
  excerpt: "At first, not drinking was something I thought about constantly. More than four years later, most days sobriety isn't something I'm doing. It's just my life.",
  publishedAt: "September 15, 2026",
  publishedDate: "2026-09-15",
  publishedTime: "10:45",
  readTime: "9 min read",
  author: "Neal",
  image: "/images/blog/i-didnt-quit-drinking-because-i-hit-rock-bottom.png",
  heroAlt: "A man enjoying a quiet September morning with coffee and his Golden Retriever on a peaceful porch.",
  relatedSlugs: [
    "you-dont-have-to-hit-rock-bottom-to-stop-drinking",
    "30-days-without-alcohol",
    "why-do-i-want-to-drink-when-nothing-is-wrong",
  ],
  sources: [],
  body: [
    { type: "paragraph", text: "I’m more than four years sober now." },
    { type: "paragraph", text: "And one of the strangest things about saying that is how little time I actually spend thinking about being sober." },
    { type: "paragraph", text: "I don't wake up thinking about alcohol." },
    { type: "paragraph", text: "I don't walk the dog thinking about alcohol." },
    { type: "paragraph", text: "I don't sit down to dinner congratulating myself for not ordering a drink." },
    { type: "paragraph", text: "Most days, sobriety isn't really something I'm doing anymore." },
    { type: "quote", text: "It's just my life." },
    { type: "paragraph", text: "That would have been very difficult for me to imagine on Day 1." },
    { type: "heading", text: "At First, Sobriety Was Loud" },
    { type: "paragraph", text: "In the beginning, not drinking takes up a lot of mental space." },
    { type: "paragraph", text: "You count days. You notice what everybody else is drinking. You think about what you're going to order before you get to the restaurant." },
    { type: "paragraph", text: "You wonder what you'll say if somebody asks why you're not drinking." },
    { type: "paragraph", text: "You start collecting firsts: first Friday night, first restaurant, first wedding, first vacation, first holiday, first football game, first really bad day, first really good day." },
    { type: "paragraph", text: "Every one of those situations can feel like a little test because alcohol used to have a role in them." },
    { type: "paragraph", text: "And when you're near the beginning, it's easy to assume you'll have to think this hard forever." },
    { type: "quote", text: "Am I really going to spend the rest of my life thinking about not drinking?" },
    { type: "heading", text: "Then the Firsts Started Disappearing" },
    { type: "paragraph", text: "Something changes once you've done enough life without alcohol." },
    { type: "paragraph", text: "The second wedding isn't your first sober wedding. The next vacation isn't your first alcohol-free vacation. Friday night stops being an experiment." },
    { type: "paragraph", text: "Dinner out becomes dinner out. Football becomes football." },
    { type: "paragraph", text: "You don't necessarily notice the exact moment these things become ordinary. They just stop requiring so much preparation." },
    { type: "paragraph", text: "One by one, the situations that once felt loaded become things you've already done." },
    { type: "heading", text: "The Old Normal Wasn't Dramatic Either" },
    { type: "paragraph", text: "When I think about drinking now, I don't picture some dramatic rock-bottom scene." },
    { type: "paragraph", text: "A lot of it was completely ordinary." },
    { type: "paragraph", text: "Come home. Put the keys down. Make dinner. Have a drink. Maybe have another. Go to bed." },
    { type: "paragraph", text: "That was part of what made changing it feel strange at first." },
    { type: "paragraph", text: "Alcohol wasn't only attached to parties or big nights. It was attached to normal routines." },
    { type: "image", src: "/images/blog/drinking-without-hitting-rock-bottom.png", alt: "An ordinary evening kitchen counter with a glass of wine, keys, wallet and dinner ingredients in warm light.", caption: "The old routine did not have to look dramatic to become familiar. Sometimes alcohol was simply part of what happened next." },

    { type: "heading", text: "Then the Routine Quietly Rewrote Itself" },
    { type: "paragraph", text: "You don't spend forever removing alcohol from the old routine. Eventually you build a new routine." },
    { type: "paragraph", text: "You cook dinner enough times without wine that cooking dinner stops reminding you of wine." },
    { type: "paragraph", text: "You watch enough games without beer that the game stops feeling incomplete." },
    { type: "paragraph", text: "You wake up enough Saturday mornings feeling good that it stops feeling like a sobriety reward. It becomes Saturday morning." },
    { type: "quote", text: "At some point, I stopped being a guy actively trying not to drink. I became a guy who just doesn't drink." },

    { type: "heading", text: "I Stopped Noticing What Everyone Else Was Drinking" },
    { type: "paragraph", text: "This might be one of the milestones nobody gives you a medal for." },
    { type: "paragraph", text: "Early on, I noticed drinks. Who had one. What they ordered. Whether I was the only person without one." },
    { type: "paragraph", text: "That awareness gradually faded." },
    { type: "paragraph", text: "Now I can be somewhere alcohol is being served and often barely register it." },
    { type: "paragraph", text: "That's not because alcohol disappeared from the world. It just stopped being the most interesting thing in the room." },

    { type: "heading", text: "Mornings Became Normal Instead of Rewards" },
    { type: "paragraph", text: "Eventually you stop waking up impressed that you aren't hungover. You just wake up." },
    { type: "paragraph", text: "Coffee. Shoes on. Take the dog out. Go somewhere. Or don't." },
    { type: "paragraph", text: "The morning belongs to you, but after enough mornings, that stops feeling extraordinary. It becomes what you expect." },

    { type: "image", src: "/images/blog/life-after-quitting-alcohol-without-rock-bottom.png", alt: "A man tying his running shoes on a sunny porch while his Golden Retriever waits beside him for a morning walk.", caption: "Eventually, getting the morning back stops feeling like a sobriety milestone. It just becomes morning." },

    { type: "heading", text: "I Don't Need Everything to Be Sober Anymore" },
    { type: "paragraph", text: "At the beginning, I think it's natural to put sober in front of everything." },
    { type: "paragraph", text: "Sober vacation. Sober wedding. Sober football. Sober dinner. Sober Friday night." },
    { type: "paragraph", text: "Those labels can be useful when something is new. But eventually I didn't need them as much." },
    { type: "paragraph", text: "It's vacation. It's a wedding. It's football. It's dinner." },
    { type: "paragraph", text: "The activity got its own identity back. Alcohol didn't need to be present, and sobriety didn't need to be announced." },

    { type: "heading", text: "Sobriety Got Smaller While My Life Got Bigger" },
    { type: "paragraph", text: "I don't mean sobriety became less important. I'm proud of it." },
    { type: "paragraph", text: "I know my day count. I built an app that literally tells me my day count." },
    { type: "paragraph", text: "But I don't want not drinking to be the biggest thing about me. That was never the goal." },
    { type: "quote", text: "The goal wasn't for sobriety to become my whole life. It was for alcohol to stop taking up so much of it." },

    { type: "heading", text: "Life Didn't Become a Recovery Ceremony" },
    { type: "paragraph", text: "Most nights now aren't inspirational. That's a compliment." },
    { type: "paragraph", text: "Dinner gets made. Work gets finished or doesn't. The dog falls asleep somewhere nearby. We watch something. I waste time on my phone. Normal life happens." },
    { type: "paragraph", text: "There isn't a soundtrack playing because I successfully made it through another alcohol-free evening." },
    { type: "paragraph", text: "I think that's what I wanted all along." },

    { type: "image", src: "/images/blog/what-life-looks-like-after-quitting-drinking.png", alt: "A peaceful lived-in home in the evening with dinner, a sparkling drink, a laptop and a Golden Retriever sleeping nearby.", caption: "Four years later, a lot of sobriety looks like this: dinner, work, the dog asleep nearby and absolutely nothing dramatic happening." },

    { type: "heading", text: "This Isn't Everyone's Experience" },
    { type: "paragraph", text: "My experience isn't a timeline for anybody else." },
    { type: "paragraph", text: "Some people deal with cravings for much longer. Some stay deeply involved in recovery communities because those communities matter enormously to them." },
    { type: "paragraph", text: "There isn't a year when everybody suddenly stops thinking about alcohol." },
    { type: "paragraph", text: "I'm only describing what happened to me. For me, the volume gradually turned down." },

    { type: "continueReading", text: "If you're still wondering whether your drinking is bad enough to justify stopping, I wrote about why you don't need to wait for rock bottom before deciding you want something different.", slug: "you-dont-have-to-hit-rock-bottom-to-stop-drinking" },

    { type: "heading", text: "What I Wish I Could Tell Myself on Day 1" },
    { type: "paragraph", text: "You won't necessarily have to think this hard forever." },
    { type: "paragraph", text: "The restaurant won't always feel like a test. Friday won't always feel strange. You won't always notice every glass in the room." },
    { type: "paragraph", text: "You won't always be collecting firsts." },
    { type: "paragraph", text: "At least, that's what happened for me. Life kept moving. Eventually sobriety moved with it." },

    { type: "heading", text: "The Number Isn't the Best Part Anymore" },
    { type: "paragraph", text: "On Day 1, 1,500 days sounded impossible. Honestly, even 30 sounded pretty big." },
    { type: "paragraph", text: "I thought getting this far would require thinking about sobriety every day for four years. It didn't." },
    { type: "paragraph", text: "Somewhere along the way, I stopped counting every decision." },
    { type: "paragraph", text: "The restaurants became restaurants again. Weddings became weddings. Friday became Friday. Mornings became mornings." },
    { type: "paragraph", text: "And alcohol became something I used to do." },
    { type: "paragraph", text: "I still know my day count. I built an app that literally tells me. And I'm proud of it." },
    { type: "paragraph", text: "But the number isn't the best part anymore." },
    { type: "quote", text: "The best part is how often I forget there's anything to count." },

    { type: "heading", text: "Frequently Asked Questions" },
    { type: "faq", question: "Does sobriety get easier over time?", answer: "It did for me, but there is no universal timeline. As I accumulated more alcohol-free experiences, situations that once required planning gradually became ordinary." },
    { type: "faq", question: "Do you still think about alcohol after four years sober?", answer: "Occasionally, but I don't spend much of an ordinary day thinking about alcohol or about being sober. For me, not drinking gradually became a normal part of life." },
    { type: "faq", question: "Do alcohol cravings eventually go away?", answer: "Craving experiences vary widely. Mine became much less central over time, but some people experience persistent or recurring cravings and may benefit from additional support." },
    { type: "faq", question: "When does sober life start feeling normal?", answer: "There isn't one milestone. For me, normality arrived gradually as I repeated familiar experiences without alcohol: dinners, weekends, weddings, vacations, stressful days and celebrations." },
    { type: "faq", question: "Do you have to make sobriety your whole identity?", answer: "No. Some people find a strong sober or recovery identity meaningful, while others prefer not drinking to be only one part of their life." },
    { type: "faq", question: "What would you tell someone on Day 1?", answer: "I would tell them that the amount of thought sobriety requires at the beginning does not necessarily last forever. For me, the firsts gradually became ordinary life." },

    { type: "featureCallout", title: "Let the Days Add Up.", text: "Nova gives you a quiet place to track your progress, notice milestones, journal what is changing and get support when you need it. The goal isn't to think about sobriety all day. It's to have something there when you do.", feature: "Nova Progress" },
  ],
};

export default theWeirdestThingAboutBeingFourYearsSober;
