import type { BlogPost } from "@/lib/blog";

const theWorldStartedDrinkingLess: BlogPost = {
  slug: "the-world-started-drinking-less-alcohol-companies-were-preparing-for-the-opposite",
  title: "The World Started Drinking Less. Alcohol Companies Were Preparing for the Opposite.",
  shortTitle: "Alcohol Companies Were Preparing for More Drinking",
  seoTitle: "Why Alcohol Sales Are Falling and Distillers Have Too Much Whiskey",
  seoDescription: "Distillers filled warehouses with whiskey, Scotch and cognac based on future demand. Now moderation, weaker markets and changing drinking habits are complicating that bet.",
  category: "News & Research",
  excerpt: "Distillers filled warehouses with whiskey, Scotch and cognac based on what they thought we would drink years later. Then drinking culture changed.",
  publishedAt: "September 2, 2026",
  publishedDate: "2026-09-02",
  publishedTime: "00:45",
  readTime: "10 min read",
  author: "Lyra",
  image: "/images/blog/alcohol-companies-whiskey-inventory-glut.png",
  heroAlt: "Rows of aging whiskey barrels filling a vast distillery warehouse, with a worker appearing small in the distance.",
  relatedSlugs: [
    "are-people-drinking-less-alcohol",
    "do-alcohol-free-drinks-help-you-drink-less",
    "is-wine-healthier-than-beer",
  ],
  sources: [
    { name: "The Wall Street Journal", title: "The World's Drinks Order Is In. Distillers Were Expecting More.", url: "https://www.wsj.com/business/retail/the-worlds-drinks-order-is-in-distillers-were-expecting-more-8ad379b3" },
    { name: "Pernod Ricard", title: "FY26 Full-Year Sales and Results", url: "https://www.pernod-ricard.com/en/media/fy26-full-year-sales-and-results" },
    { name: "Diageo", title: "2026 Preliminary Results, Year Ended 30 June 2026", url: "https://www.diageo.com/en/news-and-media/press-releases/2026/2026-preliminary-results-year-ended-30-june-2026" },
    { name: "IWSR", title: "Increased Gen Z Drinking Sustained, Boomers Drinking Moderates", url: "https://www.theiwsr.com/insight/press-release/increased-gen-z-drinking-sustained-boomers-drinking-moderates/" },
    { name: "IWSR", title: "Boomers Drive TBA Declines as Gen Z Steps Up", url: "https://www.theiwsr.com/insight/boomers-drive-tba-declines-as-gen-z-steps-up/" },
    { name: "Gallup", title: "Americans' Drinking Remains at Record Low", url: "https://news.gallup.com/poll/713534/americans-drinking-remains-record-low.aspx" },
  ],
  body: [
    { type: "paragraph", text: "Somewhere in Scotland, Kentucky and southwest France, there are warehouses full of a problem that took years to make." },
    { type: "paragraph", text: "Whiskey." },
    { type: "paragraph", text: "Cognac." },
    { type: "paragraph", text: "Scotch." },
    { type: "paragraph", text: "Lots of it." },
    { type: "paragraph", text: "The alcohol industry made a perfectly reasonable assumption several years ago:" },
    { type: "quote", text: "People were going to keep drinking." },
    { type: "paragraph", text: "So distillers filled barrels." },
    { type: "paragraph", text: "Some of those barrels needed to sit for years before anyone could sell what was inside them." },
    { type: "paragraph", text: "Then the future arrived." },
    { type: "paragraph", text: "And people weren't drinking quite the way the industry expected." },
    { type: "paragraph", text: "Now some of the world's largest alcohol companies are sitting on billions of dollars of aging spirits while cutting production, managing weaker demand and trying to figure out whether the change they're seeing is temporary or something much bigger." },
    { type: "paragraph", text: "The whiskey kept aging." },
    { type: "paragraph", text: "The drinker changed." },
    { type: "heading", text: "Whiskey Is a Prediction About the Future" },
    { type: "paragraph", text: "Most businesses can respond fairly quickly when customers want less of something." },
    { type: "paragraph", text: "Sell fewer sweaters? Order fewer next season." },
    { type: "paragraph", text: "People stop buying a certain snack? Make less of it." },
    { type: "paragraph", text: "Aged spirits don't work like that." },
    { type: "paragraph", text: "When a distiller puts whiskey or cognac into a barrel, the company is making a prediction about demand years into the future." },
    { type: "paragraph", text: "A VS cognac may require projecting demand roughly two years ahead. Many whiskies spend considerably longer aging." },
    { type: "paragraph", text: "That means a barrel sitting in a warehouse today may reflect a decision made when the world looked very different." },
    { type: "paragraph", text: "And there are a lot of barrels sitting in warehouses." },
    { type: "paragraph", text: "The Wall Street Journal recently reported that Pernod Ricard had about €7.2 billion, roughly $8.4 billion, of maturing inventory at the end of June. That was 78% more than at the end of 2019." },
    { type: "paragraph", text: "Rémy Cointreau had another €1.9 billion of inventory on its books." },
    { type: "paragraph", text: "Diageo has described approximately $8.5 billion of maturing stock already sitting on its balance sheet." },
    { type: "quote", text: "They weren't just making whiskey. They were making a bet about how we would drink years into the future." },
    { type: "heading", text: "The Bet Looked Pretty Good for a While" },
    { type: "paragraph", text: "It is easy to understand why producers became optimistic." },
    { type: "paragraph", text: "During the pandemic era and immediately afterward, premium spirits benefited from unusual consumer behavior." },
    { type: "paragraph", text: "People were drinking at home." },
    { type: "paragraph", text: "Some consumers spent money they might otherwise have spent at restaurants or on travel on nicer bottles." },
    { type: "paragraph", text: "Premiumization became one of the industry's favorite words." },
    { type: "paragraph", text: "Whiskey, tequila and other higher-end spirits appeared positioned for continued growth." },
    { type: "paragraph", text: "If you operate a business where tomorrow's bottle needs to begin aging today, waiting until demand arrives is not an option." },
    { type: "paragraph", text: "You have to anticipate it." },
    { type: "paragraph", text: "So producers laid down stock." },
    { type: "paragraph", text: "And then the environment changed." },
    {
      type: "image",
      src: "/images/blog/whiskey-production-future-demand.png",
      alt: "A distillery worker moving a whiskey barrel through an active production facility with copper equipment in the background.",
      caption: "A barrel filled today may not become a bottle for years. Aged spirits force producers to make decisions about consumers they have not met yet.",
    },
    { type: "heading", text: "The Numbers Aren't Looking Like the Forecast" },
    { type: "paragraph", text: "Pernod Ricard's latest fiscal-year results provide a useful snapshot." },
    { type: "paragraph", text: "Organic sales fell 3.9% in fiscal 2026." },
    { type: "paragraph", text: "The United States was particularly weak, with organic sales down 14%. China was weak too, while results outside the U.S. and China were more resilient." },
    { type: "paragraph", text: "The company cited a spirits-market slowdown, economic moderation, subdued consumer confidence and inventory adjustments among the pressures in the U.S." },
    { type: "paragraph", text: "Diageo's organic sales fell 2% in its fiscal year, with weaker U.S. spirits performance among the pressures on the business." },
    { type: "paragraph", text: "That's important because this is not a story where the entire planet suddenly stopped buying alcohol." },
    { type: "paragraph", text: "Some markets are growing." },
    { type: "paragraph", text: "Some brands are growing." },
    { type: "paragraph", text: "Ready-to-drink products are growing in places where traditional spirits are struggling." },
    { type: "quote", text: "The alcohol business isn't disappearing. It is becoming much harder to predict." },
    { type: "heading", text: "Americans Really Are Drinking Differently" },
    { type: "paragraph", text: "The cultural part of this story isn't imaginary." },
    { type: "paragraph", text: "Gallup's latest U.S. survey found that 54% of American adults say they drink alcohol, tied with last year's record low in its trend going back to 1939." },
    { type: "paragraph", text: "That number was 62% in 2023." },
    { type: "paragraph", text: "Gallup also found that 51% of adults now believe drinking one or two alcoholic beverages per day is bad for health." },
    { type: "paragraph", text: "And for the first time, Gallup asked about nonalcoholic alternatives." },
    { type: "paragraph", text: "Seventeen percent of Americans said they had consumed nonalcoholic beer, wine or spirits instead of alcohol during the previous year." },
    { type: "paragraph", text: "Those aren't tiny cultural signals." },
    { type: "paragraph", text: "But they still don't explain the entire warehouse problem." },
    { type: "heading", text: "No, Gen Z Didn't Kill Whiskey" },
    { type: "paragraph", text: "This is where the easy version of the story starts falling apart." },
    { type: "paragraph", text: "You've probably seen some version of the headline: Gen Z doesn't drink." },
    { type: "paragraph", text: "Current data are much messier." },
    { type: "paragraph", text: "IWSR's 2026 consumer research across major alcohol markets found that drinking participation among legal-drinking-age Gen Z consumers has risen to 74%, nearly matching the overall adult drinking rate of 76%." },
    { type: "paragraph", text: "In the United States, Gen Z participation reached 71%." },
    { type: "paragraph", text: "Meanwhile, Boomers recorded the lowest drinking participation of any generation in the survey and were the only generation reducing participation, drinking frequency and drinks per occasion at the same time." },
    { type: "paragraph", text: "So the cultural story isn't that young people stopped drinking and broke the alcohol industry." },
    { type: "quote", text: "People across generations are becoming more selective about when, how much and what they drink." },
    { type: "heading", text: "Drinking Less Doesn't Always Mean Not Drinking" },
    { type: "paragraph", text: "IWSR found something else worth paying attention to." },
    { type: "paragraph", text: "Across the markets it tracks, the average number of drinks consumed on a drinking occasion fell from 4.4 in 2024 to 3.9 in 2026." },
    { type: "paragraph", text: "The company describes moderation as increasingly embedded in consumer behavior rather than a short-lived trend." },
    { type: "paragraph", text: "That doesn't mean everybody is becoming sober." },
    { type: "paragraph", text: "Far from it." },
    { type: "paragraph", text: "Someone may still drink but have fewer drinks." },
    { type: "paragraph", text: "Someone else may drink only on weekends." },
    { type: "paragraph", text: "Someone may alternate between alcoholic and alcohol-free beer." },
    { type: "paragraph", text: "Another person might order a cocktail at dinner but skip the bottle of wine." },
    { type: "paragraph", text: "Somebody who once bought a bottle of whiskey every month might now buy one every three months." },
    { type: "paragraph", text: "For the individual, those can feel like small changes." },
    { type: "paragraph", text: "Multiply them across millions of consumers and they become an inventory problem." },
    { type: "quote", text: "The problem with predicting drinking culture is that whiskey ages more slowly than culture changes." },
    { type: "heading", text: "The Shelf Is Getting More Complicated Too" },
    { type: "paragraph", text: "Consumers aren't simply choosing between drinking and not drinking anymore." },
    { type: "paragraph", text: "They're choosing among more categories." },
    { type: "paragraph", text: "Traditional spirits." },
    { type: "paragraph", text: "Cocktails." },
    { type: "paragraph", text: "Ready-to-drink cans." },
    { type: "paragraph", text: "Alcohol-free beer." },
    { type: "paragraph", text: "Dealcoholized wine." },
    { type: "paragraph", text: "Zero-proof drinks." },
    { type: "paragraph", text: "Hard seltzers." },
    { type: "paragraph", text: "Lower-alcohol products." },
    { type: "paragraph", text: "And whatever arrives next." },
    { type: "paragraph", text: "Pernod Ricard's traditional business struggled in fiscal 2026, but its ready-to-drink portfolio grew 12%, including strong growth across Canada, Australia and Western Europe." },
    { type: "paragraph", text: "IWSR similarly reports that ready-to-drink and no-alcohol products were exceptions to broader beverage-alcohol volume declines in 2025." },
    { type: "paragraph", text: "That doesn't necessarily mean the future is alcohol-free." },
    { type: "paragraph", text: "It may mean the future has more options competing for the same occasion." },
    {
      type: "image",
      src: "/images/blog/changing-drinking-habits-alcohol-industry.png",
      alt: "Four friends talking over dinner at a busy restaurant with a mix of alcoholic and alcohol-free drink choices on the table.",
      caption: "The drinking occasion is not disappearing. What counts as a normal choice within it is becoming more varied.",
    },
    { type: "heading", text: "But Moderation Isn't the Whole Story" },
    { type: "paragraph", text: "It would be convenient for Nova to look at warehouses full of whiskey and declare: See? Everyone is drinking less." },
    { type: "paragraph", text: "The evidence doesn't justify that conclusion." },
    { type: "paragraph", text: "There are major economic forces involved." },
    { type: "paragraph", text: "Pernod Ricard specifically pointed to economic moderation and subdued consumer confidence in the United States." },
    { type: "paragraph", text: "China has been weak." },
    { type: "paragraph", text: "Tariffs and trade disputes have complicated global spirits markets." },
    { type: "paragraph", text: "Consumers under financial pressure may simply buy fewer premium bottles." },
    { type: "paragraph", text: "Retailers and distributors can reduce inventory even when consumers haven't changed as dramatically." },
    { type: "paragraph", text: "Post-pandemic purchasing patterns also had to normalize eventually." },
    { type: "paragraph", text: "Different countries are moving in different directions." },
    { type: "paragraph", text: "And some alcohol categories are performing considerably better than others." },
    { type: "paragraph", text: "The moderation trend matters. It just isn't the only thing happening." },
    { type: "paragraph", text: "That's usually the problem with cultural shifts. They rarely arrive alone." },
    { type: "heading", text: "So What Do You Do With $8.5 Billion of Aging Alcohol?" },
    { type: "paragraph", text: "You don't pour it down the drain." },
    { type: "paragraph", text: "And you probably don't want to flood the market with cheap whiskey either." },
    { type: "paragraph", text: "Aggressive discounting could damage premium brands and start a price war." },
    { type: "paragraph", text: "Instead, major producers are reducing how much new liquid they make." },
    { type: "paragraph", text: "Diageo says it has scaled back production and distillation, particularly in Scotch, North American whiskey and tequila, while it works through existing maturing inventory." },
    { type: "paragraph", text: "The company has also said the amount of liquid it plans to put into barrels over the next three years will be more than 50% lower than in the prior three-year period." },
    { type: "paragraph", text: "The Wall Street Journal reports that producers are cutting output rather than trying to unload all of their aging stock quickly." },
    { type: "paragraph", text: "That's the strange thing about this particular business problem." },
    { type: "paragraph", text: "Today's weak demand doesn't merely affect what companies sell today." },
    { type: "paragraph", text: "It changes how much whiskey they make for people who may not walk into a liquor store until years from now." },
    { type: "heading", text: "The Bar Isn't Empty. The Default Is Changing." },
    { type: "paragraph", text: "There is a temptation whenever drinking declines to imagine a future where bars disappear and everybody carries sparkling water." },
    { type: "paragraph", text: "That's not what the evidence shows." },
    { type: "paragraph", text: "People still drink." },
    { type: "paragraph", text: "Gen Z still drinks." },
    { type: "paragraph", text: "Cocktails remain popular." },
    { type: "paragraph", text: "Premium bottles still sell." },
    { type: "paragraph", text: "But something subtler may be happening." },
    { type: "paragraph", text: "Alcohol is becoming less automatic for more people." },
    { type: "paragraph", text: "The drink at dinner doesn't always have to contain alcohol." },
    { type: "paragraph", text: "Friday doesn't automatically mean five drinks." },
    { type: "paragraph", text: "A celebration doesn't require everyone to make the same choice." },
    { type: "paragraph", text: "A person can drink sometimes and choose not to drink other times without needing to adopt a permanent identity around either decision." },
    { type: "quote", text: "People aren't necessarily replacing drinking with sobriety. They're replacing one default with more choices." },
    { type: "heading", text: "Why This Matters Beyond Alcohol Companies" },
    { type: "paragraph", text: "A warehouse full of whiskey might seem pretty far removed from someone deciding what to drink tonight." },
    { type: "paragraph", text: "But those barrels are physical evidence of expectations." },
    { type: "paragraph", text: "Companies invest billions based on assumptions about what people will want years later." },
    { type: "paragraph", text: "How often they'll drink." },
    { type: "paragraph", text: "What they'll drink." },
    { type: "paragraph", text: "What they'll pay." },
    { type: "paragraph", text: "Which traditions will survive." },
    { type: "paragraph", text: "Which generations will inherit the habits of the ones before them." },
    { type: "paragraph", text: "And right now, some of those assumptions are being rewritten." },
    { type: "paragraph", text: "Not because alcohol disappeared." },
    { type: "paragraph", text: "Because behavior became less predictable." },
    { type: "heading", text: "Maybe the Biggest Change Is the Assumption" },
    { type: "paragraph", text: "For a long time, the alcohol industry could make a fairly comfortable prediction about younger consumers." },
    { type: "paragraph", text: "They would get older." },
    { type: "paragraph", text: "Their incomes would rise." },
    { type: "paragraph", text: "Their tastes would mature." },
    { type: "paragraph", text: "And eventually they would buy the good bottle." },
    { type: "paragraph", text: "Maybe that still happens." },
    { type: "paragraph", text: "Maybe today's inventory glut eventually looks like a temporary correction caused by economics, geopolitics and post-pandemic excess." },
    { type: "paragraph", text: "Maybe moderation continues and permanently changes how often people drink." },
    { type: "paragraph", text: "Maybe growing markets elsewhere absorb some of the industry's future production." },
    { type: "paragraph", text: "Nobody knows yet." },
    { type: "paragraph", text: "That's what makes warehouses full of aging spirits so fascinating." },
    { type: "paragraph", text: "They are not merely inventory." },
    { type: "paragraph", text: "They're predictions." },
    {
      type: "image",
      src: "/images/blog/whiskey-barrels-aging-demand-decline.png",
      alt: "A traditional distillery warehouse at blue hour with warm light revealing rows of whiskey barrels inside.",
      caption: "The barrels keep aging while producers wait to learn what future drinkers will actually want.",
    },
    { type: "paragraph", text: "Somewhere tonight, millions of barrels are continuing to sit quietly in the dark." },
    { type: "paragraph", text: "The whiskey is doing exactly what its makers expected." },
    { type: "quote", text: "The drinker is the part they are still trying to predict." },
    {
      type: "continueReading",
      text: "The inventory problem is arriving during a broader shift in drinking culture. We also looked at why alcohol consumption is changing and what the numbers actually show.",
      slug: "are-people-drinking-less-alcohol",
    },

    { type: "heading", text: "Frequently Asked Questions" },
    {
      type: "faq",
      question: "Why do alcohol companies have too much whiskey right now?",
      answer: "Aged-spirit producers have to decide how much whiskey, Scotch or cognac to make years before it can be sold. Major companies increased maturing inventory when future demand looked stronger. Weaker spirits demand, economic pressure, inventory corrections and changing drinking behavior have since left some producers carrying unusually large stocks.",
    },
    {
      type: "faq",
      question: "Are Americans really drinking less alcohol?",
      answer: "Gallup reported in August 2026 that 54% of U.S. adults say they drink alcohol, tied with the lowest level in its trend dating to 1939. The share fell from 62% in 2023. Gallup also found growing concern about alcohol's health effects and increasing use of nonalcoholic alternatives.",
    },
    {
      type: "faq",
      question: "Is Gen Z drinking less than older generations?",
      answer: "Not as simply as popular headlines suggest. IWSR's 2026 research found legal-drinking-age Gen Z participation at 74% across major markets and 71% in the United States. Boomers were the only generation in its survey reducing participation, frequency and drinks per occasion at the same time.",
    },
    {
      type: "faq",
      question: "Why can't distillers simply make less whiskey?",
      answer: "They can, and some already are. The difficulty is timing. Whiskey and other aged spirits made today may not reach consumers for years, while barrels already aging represent production decisions made in the past. Cutting production today primarily changes future supply rather than eliminating existing inventory.",
    },
    {
      type: "faq",
      question: "Is alcohol disappearing?",
      answer: "No. Alcohol remains a large global market, and consumption patterns vary significantly by country, generation and beverage category. The more interesting shift is moderation: many consumers are drinking less frequently, consuming fewer drinks per occasion or choosing among alcoholic and nonalcoholic options rather than abandoning alcohol entirely.",
    },
    {
      type: "featureCallout",
      title: "More Choices, Less Autopilot",
      text: "Nova is built for people who are sober, cutting back or simply paying closer attention to alcohol. The goal is not to tell you what belongs in your glass. It is to help you notice your patterns and make the choice intentionally.",
      feature: "Nova",
    },
  ],
};

export default theWorldStartedDrinkingLess;
