import type { BlogPost } from "@/lib/blog";

const youDontHaveToWaitUntilJanuary: BlogPost = {
  slug: "you-dont-have-to-wait-until-january-to-change-your-drinking",
  title: "You Don't Have to Wait Until January to Change Your Drinking",
  shortTitle: "You Don't Have to Wait Until January",
  seoTitle: "You Don't Have to Wait Until January to Change Your Drinking | Nova",
  seoDescription: "September can feel like a fresh start. Neal shares why you don't need January, a dramatic declaration, or a permanent label to start changing your relationship with alcohol.",
  category: "Sobriety & Life",
  excerpt: "January gets all the credit for fresh starts. But September might be just as good a time to notice your drinking, question a pattern, and decide what you want to do next.",
  publishedAt: "September 3, 2026",
  publishedDate: "2026-09-03",
  publishedTime: "11:20",
  readTime: "8 min read",
  author: "Neal",
  image: "/images/blog/september-reset-change-your-drinking.png",
  heroAlt: "A quiet early-September lake at golden hour with two Adirondack chairs on a weathered dock and a kayak pulled onto shore.",
  relatedSlugs: ["is-being-sober-cool-now", "what-does-an-alcohol-craving-really-mean", "do-alcohol-free-drinks-help-you-drink-less"],
  sources: [
    { name: "Real Simple", title: "The September Reset Is Real: Here's Why You Suddenly Want to Organize Your Entire Life", url: "https://www.realsimple.com/why-september-makes-you-want-to-reset-your-life-12074718" },
    { name: "National Highway Traffic Safety Administration", title: "Drive Sober or Get Pulled Over", url: "https://www.nhtsa.gov/campaign/drive-sober-or-get-pulled-over" },
    { name: "National Highway Traffic Safety Administration", title: "Drive Sober or Get Pulled Over: Labor Day 2026", url: "https://www.nhtsa.gov/press-releases/drive-sober-or-get-pulled-over-labor-day-2026" },
  ],
  body: [
    { type: "paragraph", text: "I've always thought January gets too much credit." },
    { type: "paragraph", text: "We treat January 1 like it's the one day of the year when we're allowed to look at our lives and decide something needs to change." },
    { type: "paragraph", text: "New year." },
    { type: "paragraph", text: "New habits." },
    { type: "paragraph", text: "New promises." },
    { type: "paragraph", text: "New version of yourself." },
    { type: "paragraph", text: "Then September shows up without nearly as much attention." },
    { type: "paragraph", text: "And honestly, September has always felt like more of a reset to me." },
    { type: "paragraph", text: "Summer starts winding down. Vacations end. Kids go back to school. Football comes back. The mornings start feeling a little different. Even if the weather hasn't completely changed yet, you can tell something is about to." },
    { type: "paragraph", text: "Life starts getting back into a routine." },
    { type: "paragraph", text: "And maybe that's not a bad time to ask yourself a pretty simple question:" },
    { type: "quote", text: "Do I want to keep drinking the same way I did all summer?" },
    { type: "paragraph", text: "You don't have to know the answer yet." },
    { type: "heading", text: "September Feels Like Starting Over" },
    { type: "paragraph", text: "There's apparently a reason September can feel this way." },
    { type: "paragraph", text: "Psychologists sometimes talk about the fresh-start effect. Certain moments create a mental line between what came before and what comes next. Researchers call them temporal landmarks." },
    { type: "paragraph", text: "New Year's Day is an obvious one." },
    { type: "paragraph", text: "A birthday can be one." },
    { type: "paragraph", text: "A Monday can even be one." },
    { type: "paragraph", text: "And the beginning of a new season can work the same way." },
    { type: "paragraph", text: "Fresh coverage this week looked specifically at why September can create that feeling. Summer ends, schedules become more structured again, and decades of associating September with a new school year may leave us with a surprisingly persistent sense that something new is beginning." },
    { type: "paragraph", text: "I like that." },
    { type: "paragraph", text: "Not because I think September has some magical power to make changing easier." },
    { type: "paragraph", text: "But because I don't think January does either." },
    { type: "paragraph", text: "Sometimes you just need a reason to stop running on autopilot long enough to notice what you're doing." },
    { type: "image", src: "/images/blog/september-routine-fresh-start.png", alt: "A middle-aged man tying his shoes near the front door in soft September morning light as he gets ready to leave the house.", caption: "September has a way of putting ordinary routines back into focus. Sometimes that is enough to make you notice a habit you've stopped thinking about." },
    { type: "heading", text: "Summer Makes It Pretty Easy Not to Notice" },
    { type: "paragraph", text: "Summer has a way of making everything feel like an occasion." },
    { type: "paragraph", text: "It's Friday." },
    { type: "paragraph", text: "We're grilling." },
    { type: "paragraph", text: "We're at the lake." },
    { type: "paragraph", text: "We're on vacation." },
    { type: "paragraph", text: "Someone's getting married." },
    { type: "paragraph", text: "People are coming over." },
    { type: "paragraph", text: "It's beautiful outside." },
    { type: "paragraph", text: "Let's have a drink." },
    { type: "paragraph", text: "None of those things are inherently bad." },
    { type: "paragraph", text: "But enough occasions strung together can quietly become a routine." },
    { type: "paragraph", text: "And routines are funny because eventually you stop making a decision." },
    { type: "paragraph", text: "You just do what you normally do." },
    { type: "paragraph", text: "That was certainly true for me with drinking." },
    { type: "paragraph", text: "I didn't wake up every afternoon and carefully consider whether alcohol was going to make my evening better." },
    { type: "paragraph", text: "At some point, drinking was simply something I did." },
    { type: "paragraph", text: "That's one of the things I've become much more aware of after four years sober." },
    { type: "paragraph", text: "Sometimes the biggest change isn't saying no to a drink." },
    { type: "paragraph", text: "It's realizing there was a decision there in the first place." },
    { type: "quote", text: "You can't really change a pattern until you notice you're in one." },
    { type: "heading", text: "You Don't Have to Quit Forever" },
    { type: "paragraph", text: "I think this is where conversations about alcohol become unnecessarily intimidating." },
    { type: "paragraph", text: "Someone thinks: Maybe I'm drinking more than I want to." },
    { type: "paragraph", text: "And somehow that thought immediately turns into: Does this mean I can never drink again?" },
    { type: "paragraph", text: "Those are two very different questions." },
    { type: "paragraph", text: "You don't have to decide the rest of your life because you're curious about September." },
    { type: "paragraph", text: "Maybe you want to drink less." },
    { type: "paragraph", text: "Maybe you want to take a week off." },
    { type: "paragraph", text: "Maybe you want to stop drinking during the week." },
    { type: "paragraph", text: "Maybe you want to see what a football Sunday feels like without beer." },
    { type: "paragraph", text: "Maybe you're tired of losing Saturday mornings." },
    { type: "paragraph", text: "Maybe you're curious what happens if you keep going after seven days." },
    { type: "paragraph", text: "Or maybe you already know you're done." },
    { type: "paragraph", text: "Everyone arrives at this from somewhere different." },
    { type: "paragraph", text: "I stopped drinking completely." },
    { type: "paragraph", text: "That doesn't mean everyone reading this needs to." },
    { type: "paragraph", text: "What I do think is worth asking is whether the way you're drinking right now is something you're choosing, or something you've simply gotten used to doing." },
    { type: "paragraph", text: "That's a much less dramatic question." },
    { type: "paragraph", text: "And sometimes it's a much more useful one." },
    { type: "heading", text: "Labor Day Doesn't Have to Be the Last Hurrah" },
    { type: "paragraph", text: "Labor Day weekend is coming." },
    { type: "paragraph", text: "For a lot of people, it's the unofficial end of summer." },
    { type: "paragraph", text: "Cookouts. Pools. Boats. Football. Friends. One more long weekend before everything starts feeling like fall." },
    { type: "paragraph", text: "There's an easy way to look at a weekend like that:" },
    { type: "paragraph", text: "I'll start after Labor Day." },
    { type: "paragraph", text: "I understand that thinking." },
    { type: "paragraph", text: "But Labor Day doesn't have to become your last wild weekend before you suddenly become a completely different person on Tuesday." },
    { type: "paragraph", text: "It also doesn't have to become some enormous test of whether you can survive a cookout without drinking." },
    { type: "paragraph", text: "It's just a weekend." },
    { type: "paragraph", text: "If you want the beer, that's your decision." },
    { type: "paragraph", text: "If you're curious what the afternoon feels like without it, that's a decision too." },
    { type: "quote", text: "September doesn't need a declaration. It can just be the month you start paying attention." },
    { type: "paragraph", text: "And if you are drinking this weekend, there's one decision that shouldn't be left until later." },
    { type: "paragraph", text: "Figure out how you're getting home first." },
    { type: "paragraph", text: "NHTSA's Labor Day Drive Sober or Get Pulled Over campaign runs through September 7. The agency reports that 505 people died in traffic crashes during the 2024 Labor Day weekend, and 33% of those deaths involved a drunk driver." },
    { type: "paragraph", text: "If you're drinking, arrange a sober driver, rideshare, taxi or another safe way home before the first drink." },
    { type: "paragraph", text: "That part doesn't need to be complicated." },
    { type: "image", src: "/images/blog/labor-day-drinking-choices.png", alt: "Friends and families talking at a relaxed Labor Day backyard cookout with food on the grill and a mix of drink choices.", caption: "A different choice doesn't have to turn the whole afternoon into a sobriety story. Sometimes you choose what you want and keep talking." },
    { type: "heading", text: "I Wish I Had Paid Attention Earlier" },
    { type: "paragraph", text: "Looking back, I don't think my relationship with alcohol changed overnight." },
    { type: "paragraph", text: "My awareness of it did." },
    { type: "paragraph", text: "There were plenty of little things I could have noticed earlier." },
    { type: "paragraph", text: "How often I drank." },
    { type: "paragraph", text: "How much mental space went into thinking about drinking." },
    { type: "paragraph", text: "How normal it felt to plan evenings around it." },
    { type: "paragraph", text: "How many mornings started with some version of: I probably didn't need that last one." },
    { type: "paragraph", text: "None of those moments individually felt dramatic enough to demand some huge life change." },
    { type: "paragraph", text: "That's probably why they're easy to ignore." },
    { type: "paragraph", text: "You can always find someone who drinks more than you." },
    { type: "paragraph", text: "You can always point to the nights when everything was completely fine." },
    { type: "paragraph", text: "You can always tell yourself you'll cut back next week." },
    { type: "paragraph", text: "Eventually I stopped comparing my drinking to what would qualify as a serious problem and started thinking about a much simpler question:" },
    { type: "quote", text: "Was drinking making my life better?" },
    { type: "paragraph", text: "For me, eventually, the answer became no." },
    { type: "paragraph", text: "That answer didn't require me to prove anything about how bad my drinking was." },
    { type: "paragraph", text: "It was enough." },
    { type: "heading", text: "Small Changes Count More Than We Give Them Credit For" },
    { type: "paragraph", text: "I think we tend to celebrate dramatic changes because they're easier to see." },
    { type: "paragraph", text: "Thirty days." },
    { type: "paragraph", text: "One year." },
    { type: "paragraph", text: "Five years." },
    { type: "paragraph", text: "Those milestones matter." },
    { type: "paragraph", text: "I'm proud of mine." },
    { type: "paragraph", text: "But every long streak started with one pretty ordinary day." },
    { type: "paragraph", text: "Nobody wakes up four years sober." },
    { type: "paragraph", text: "You get there by waking up sober today." },
    { type: "paragraph", text: "Then eventually there are enough todays behind you that you look back and realize something changed." },
    { type: "paragraph", text: "The same is true if you're cutting back." },
    { type: "paragraph", text: "One alcohol-free night matters." },
    { type: "paragraph", text: "One weekend where you have two drinks instead of six matters." },
    { type: "paragraph", text: "Not automatically pouring wine while you cook dinner matters." },
    { type: "paragraph", text: "Noticing that Friday is usually your difficult night matters." },
    { type: "paragraph", text: "Those things aren't impressive enough for some giant announcement." },
    { type: "paragraph", text: "They're just information." },
    { type: "paragraph", text: "And information gives you choices." },
    { type: "continueReading", text: "If changing your drinking starts with noticing what happens in ordinary social situations, I wrote about how sobriety eventually changed the way I feel in a room full of people drinking.", slug: "is-being-sober-cool-now" },
    { type: "heading", text: "You Don't Need to Be Perfect at This" },
    { type: "paragraph", text: "This might be the part I care about most." },
    { type: "paragraph", text: "If you decide September is going to look different and then you drink, September isn't ruined." },
    { type: "paragraph", text: "You didn't fail the month." },
    { type: "paragraph", text: "You learned something." },
    { type: "paragraph", text: "Maybe you discover Saturday nights are harder than Tuesdays." },
    { type: "paragraph", text: "Maybe certain people make drinking feel automatic." },
    { type: "paragraph", text: "Maybe having something else cold in the refrigerator helps." },
    { type: "paragraph", text: "Maybe you realize you're actually happier not drinking." },
    { type: "paragraph", text: "Maybe you realize you're not ready." },
    { type: "paragraph", text: "Pay attention to that too." },
    { type: "paragraph", text: "The fresh-start idea is useful partly because a new beginning doesn't need to become an unrealistic total reinvention. Smaller, flexible changes can give you somewhere to begin without demanding perfection immediately." },
    { type: "paragraph", text: "I think that applies especially well here." },
    { type: "quote", text: "You don't have to prove anything. You can just get curious." },
    { type: "heading", text: "January Will Still Be There" },
    { type: "paragraph", text: "Maybe nothing changes for you this September." },
    { type: "paragraph", text: "That's okay." },
    { type: "paragraph", text: "Maybe you drink exactly the way you did in August." },
    { type: "paragraph", text: "Maybe you have one less." },
    { type: "paragraph", text: "Maybe you skip a night." },
    { type: "paragraph", text: "Maybe you start noticing patterns you hadn't paid attention to before." },
    { type: "paragraph", text: "Maybe you wake up one morning and realize you've quietly put together a week." },
    { type: "paragraph", text: "And maybe that week makes you curious about another one." },
    { type: "paragraph", text: "You don't have to know where it's going." },
    { type: "paragraph", text: "You don't need a label before you begin." },
    { type: "paragraph", text: "You don't need to make an announcement." },
    { type: "paragraph", text: "And you definitely don't need to wait four more months for the calendar to give you permission." },
    { type: "quote", text: "January isn't the only month you're allowed to begin." },
    { type: "image", src: "/images/blog/starting-over-without-alcohol.png", alt: "A man walking with a Golden Retriever along a quiet woodland trail in early September as the first leaves begin to change.", caption: "You don't have to know exactly where a change is going before you take the next ordinary step." },

    { type: "heading", text: "Frequently Asked Questions" },
    { type: "faq", question: "Do I have to quit drinking forever to start changing my relationship with alcohol?", answer: "No. Some people decide to stop completely, while others begin by cutting back, taking a break, changing when they drink, or simply paying closer attention to their patterns. You do not have to make a permanent declaration before you start learning what works for you." },
    { type: "faq", question: "Why can September feel like a fresh start?", answer: "Behavioral researchers have described a fresh-start effect around temporal landmarks such as a new week, month, year, birthday, or season. September can feel especially transitional because summer routines end, school and work schedules become more structured, and many people associate the month with beginning again." },
    { type: "faq", question: "What if I decide to drink less and then have a drink?", answer: "One drinking day does not erase everything you noticed or learned. Pay attention to what happened, what made drinking easier or harder to avoid, and what you want to try next. Changing a pattern does not require a perfect month." },
    { type: "faq", question: "How can I start paying attention to my drinking?", answer: "Notice when you drink, what was happening beforehand, how much you planned to have versus how much you actually had, and how you felt afterward. Looking for repeated days, situations, emotions, or routines can make an automatic pattern easier to see." },
    { type: "faq", question: "How can I stay safe if I drink over Labor Day weekend?", answer: "Plan your transportation before drinking. NHTSA recommends using a designated sober driver, rideshare, taxi, public transportation, or another safe option rather than driving after consuming alcohol or another impairing substance." },

    { type: "featureCallout", title: "Notice the pattern before you judge it.", text: "Nova's Patterns view helps you see your drinking and alcohol-free days over time. The point isn't to make a red day a failure or a green day a rule. It's to make a pattern visible enough that you can decide what you want to do with it.", feature: "Nova Patterns" },
  ],
};

export default youDontHaveToWaitUntilJanuary;
